/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */

export interface ActiveSpellDto {
  id?: string;
  mapId?: string;
  /** @nullable */
  spellIndex?: string | null;
  /** @nullable */
  spellName?: string | null;
  originGridX?: number;
  originGridY?: number;
  radiusInCells?: number;
  /** @nullable */
  shape?: string | null;
  /** @nullable */
  colorHex?: string | null;
  requiresConcentration?: boolean;
  /** @nullable */
  casterCharacterId?: string | null;
}
