/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */

export type GetApiCompendiumSpellsParams = {
/**
 * Optional search text for the spell name.
 */
query?: string;
/**
 * Optional spell level filter (0-9).
 */
level?: number;
};
