/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */

export interface GridDto {
  id?: string;
  mapId?: string;
  cellSizeInPixels?: number;
  columns?: number;
  rows?: number;
  /** @nullable */
  lineColor?: string | null;
  lineOpacity?: number;
  offsetX?: number;
  offsetY?: number;
}
