/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */

export interface MapTokenDto {
  id?: string;
  mapId?: string;
  /** @nullable */
  characterId?: string | null;
  /** @nullable */
  gameSessionId?: string | null;
  /** @nullable */
  monsterIndex?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  tokenImageUrl?: string | null;
  gridX?: number;
  gridY?: number;
  sizeInCells?: number;
  currentHp?: number;
  maxHp?: number;
  armorClass?: number;
  isVisibleToPlayers?: boolean;
  isLocked?: boolean;
}
