/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */

export interface ParticipantDto {
  id?: string;
  /** @nullable */
  playerId?: string | null;
  /** @nullable */
  playerName?: string | null;
  /** @nullable */
  selectedCharacterId?: string | null;
  isDungeonMaster?: boolean;
}
