/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */

export interface SpellCastEventDto {
  eventId?: string;
  mapId?: string;
  /** @nullable */
  spellIndex?: string | null;
  /** @nullable */
  spellName?: string | null;
  targetGridX?: number;
  targetGridY?: number;
  radiusInCells?: number;
  /** @nullable */
  areaShape?: string | null;
  /** @nullable */
  colorHex?: string | null;
  isPersistent?: boolean;
  /** @nullable */
  activeSpellId?: string | null;
}
