/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSessionDto,
  GameSessionDto,
  JoinSessionDto,
  PatchApiGameSessionIdActiveMapParams
} from '../../model';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type postApiGameSessionResponse200TextPlain = {
  data: GameSessionDto
  status: 200
}

export type postApiGameSessionResponse200ApplicationJson = {
  data: GameSessionDto
  status: 200
}

export type postApiGameSessionResponse200TextJson = {
  data: GameSessionDto
  status: 200
}

export type postApiGameSessionResponseSuccess = (postApiGameSessionResponse200TextPlain | postApiGameSessionResponse200ApplicationJson | postApiGameSessionResponse200TextJson) & {
  headers: Headers;
};
;

export type postApiGameSessionResponse = (postApiGameSessionResponseSuccess)

export const getPostApiGameSessionUrl = () => {




  return `/api/GameSession`
}

/**
 * @summary Creates a new game session with a generated 6-character room code.
 */
export const postApiGameSession = async (createSessionDto?: CreateSessionDto, options?: Parameters<typeof customInstance>[1]): Promise<postApiGameSessionResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<postApiGameSessionResponse>(getPostApiGameSessionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createSessionDto)
  }
);}





export const getPostApiGameSessionMutationKey = () => ['postApiGameSession'] as const;

export const getPostApiGameSessionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGameSession>>, TError,PostApiGameSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiGameSession>>, TError,PostApiGameSessionMutationVariables, TContext> => {

const mutationKey = getPostApiGameSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiGameSession>>, PostApiGameSessionMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiGameSession(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiGameSessionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGameSession>>>
    export type PostApiGameSessionMutationBody = CreateSessionDto | undefined
    export type PostApiGameSessionMutationError = unknown
    export type PostApiGameSessionMutationVariables = {data?: CreateSessionDto}

    /**
 * @summary Creates a new game session with a generated 6-character room code.
 */
export const usePostApiGameSession = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGameSession>>, TError,PostApiGameSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiGameSession>>,
        TError,
        PostApiGameSessionMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiGameSessionMutationOptions(options), queryClient);
    }
    export type getApiGameSessionIdResponse200TextPlain = {
  data: GameSessionDto
  status: 200
}

export type getApiGameSessionIdResponse200ApplicationJson = {
  data: GameSessionDto
  status: 200
}

export type getApiGameSessionIdResponse200TextJson = {
  data: GameSessionDto
  status: 200
}

export type getApiGameSessionIdResponseSuccess = (getApiGameSessionIdResponse200TextPlain | getApiGameSessionIdResponse200ApplicationJson | getApiGameSessionIdResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiGameSessionIdResponse = (getApiGameSessionIdResponseSuccess)

export const getGetApiGameSessionIdUrl = (id: string,) => {




  return `/api/GameSession/${id}`
}

/**
 * @summary Retrieves a game session by its unique ID, including connected participants.
 */
export const getApiGameSessionId = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<getApiGameSessionIdResponse> => {

  return customInstance<getApiGameSessionIdResponse>(getGetApiGameSessionIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiGameSessionIdQueryKey = (id: string,) => {
    return [
    `/api/GameSession/${id}`
    ] as const;
    }


export const getGetApiGameSessionIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiGameSessionId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGameSessionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiGameSessionIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiGameSessionId>>> = ({ signal }) => getApiGameSessionId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiGameSessionId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiGameSessionIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiGameSessionId>>>
export type GetApiGameSessionIdQueryError = unknown


export function useGetApiGameSessionId<TData = Awaited<ReturnType<typeof getApiGameSessionId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGameSessionId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGameSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiGameSessionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiGameSessionId<TData = Awaited<ReturnType<typeof getApiGameSessionId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGameSessionId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGameSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiGameSessionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiGameSessionId<TData = Awaited<ReturnType<typeof getApiGameSessionId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGameSessionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves a game session by its unique ID, including connected participants.
 */

export function useGetApiGameSessionId<TData = Awaited<ReturnType<typeof getApiGameSessionId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGameSessionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiGameSessionIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiGameSessionJoinResponse200TextPlain = {
  data: GameSessionDto
  status: 200
}

export type postApiGameSessionJoinResponse200ApplicationJson = {
  data: GameSessionDto
  status: 200
}

export type postApiGameSessionJoinResponse200TextJson = {
  data: GameSessionDto
  status: 200
}

export type postApiGameSessionJoinResponseSuccess = (postApiGameSessionJoinResponse200TextPlain | postApiGameSessionJoinResponse200ApplicationJson | postApiGameSessionJoinResponse200TextJson) & {
  headers: Headers;
};
;

export type postApiGameSessionJoinResponse = (postApiGameSessionJoinResponseSuccess)

export const getPostApiGameSessionJoinUrl = () => {




  return `/api/GameSession/join`
}

/**
 * @summary Joins an existing game session using the 6-character room code.
 */
export const postApiGameSessionJoin = async (joinSessionDto?: JoinSessionDto, options?: Parameters<typeof customInstance>[1]): Promise<postApiGameSessionJoinResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<postApiGameSessionJoinResponse>(getPostApiGameSessionJoinUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(joinSessionDto)
  }
);}





export const getPostApiGameSessionJoinMutationKey = () => ['postApiGameSessionJoin'] as const;

export const getPostApiGameSessionJoinMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGameSessionJoin>>, TError,PostApiGameSessionJoinMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiGameSessionJoin>>, TError,PostApiGameSessionJoinMutationVariables, TContext> => {

const mutationKey = getPostApiGameSessionJoinMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiGameSessionJoin>>, PostApiGameSessionJoinMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiGameSessionJoin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiGameSessionJoinMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGameSessionJoin>>>
    export type PostApiGameSessionJoinMutationBody = JoinSessionDto | undefined
    export type PostApiGameSessionJoinMutationError = unknown
    export type PostApiGameSessionJoinMutationVariables = {data?: JoinSessionDto}

    /**
 * @summary Joins an existing game session using the 6-character room code.
 */
export const usePostApiGameSessionJoin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGameSessionJoin>>, TError,PostApiGameSessionJoinMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiGameSessionJoin>>,
        TError,
        PostApiGameSessionJoinMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiGameSessionJoinMutationOptions(options), queryClient);
    }
    export type postApiGameSessionSessionIdAddMapMapIdResponse200 = {
  data: void
  status: 200
}

export type postApiGameSessionSessionIdAddMapMapIdResponseSuccess = (postApiGameSessionSessionIdAddMapMapIdResponse200) & {
  headers: Headers;
};
;

export type postApiGameSessionSessionIdAddMapMapIdResponse = (postApiGameSessionSessionIdAddMapMapIdResponseSuccess)

export const getPostApiGameSessionSessionIdAddMapMapIdUrl = (sessionId: string,
    mapId: string,) => {




  return `/api/GameSession/${sessionId}/add-map/${mapId}`
}

export const postApiGameSessionSessionIdAddMapMapId = async (sessionId: string,
    mapId: string, options?: Parameters<typeof customInstance>[1]): Promise<postApiGameSessionSessionIdAddMapMapIdResponse> => {

  return customInstance<postApiGameSessionSessionIdAddMapMapIdResponse>(getPostApiGameSessionSessionIdAddMapMapIdUrl(sessionId,mapId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiGameSessionSessionIdAddMapMapIdMutationKey = () => ['postApiGameSessionSessionIdAddMapMapId'] as const;

export const getPostApiGameSessionSessionIdAddMapMapIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGameSessionSessionIdAddMapMapId>>, TError,PostApiGameSessionSessionIdAddMapMapIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiGameSessionSessionIdAddMapMapId>>, TError,PostApiGameSessionSessionIdAddMapMapIdMutationVariables, TContext> => {

const mutationKey = getPostApiGameSessionSessionIdAddMapMapIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiGameSessionSessionIdAddMapMapId>>, PostApiGameSessionSessionIdAddMapMapIdMutationVariables> = (props) => {
          const {sessionId,mapId} = props ?? {};

          return  postApiGameSessionSessionIdAddMapMapId(sessionId,mapId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiGameSessionSessionIdAddMapMapIdMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGameSessionSessionIdAddMapMapId>>>

    export type PostApiGameSessionSessionIdAddMapMapIdMutationError = unknown
    export type PostApiGameSessionSessionIdAddMapMapIdMutationVariables = {sessionId: string;mapId: string}

    export const usePostApiGameSessionSessionIdAddMapMapId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGameSessionSessionIdAddMapMapId>>, TError,PostApiGameSessionSessionIdAddMapMapIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiGameSessionSessionIdAddMapMapId>>,
        TError,
        PostApiGameSessionSessionIdAddMapMapIdMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiGameSessionSessionIdAddMapMapIdMutationOptions(options), queryClient);
    }
    export type patchApiGameSessionIdActiveMapResponse200 = {
  data: void
  status: 200
}

export type patchApiGameSessionIdActiveMapResponseSuccess = (patchApiGameSessionIdActiveMapResponse200) & {
  headers: Headers;
};
;

export type patchApiGameSessionIdActiveMapResponse = (patchApiGameSessionIdActiveMapResponseSuccess)

export const getPatchApiGameSessionIdActiveMapUrl = (id: string,
    params?: PatchApiGameSessionIdActiveMapParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/GameSession/${id}/active-map?${stringifiedParams}` : `/api/GameSession/${id}/active-map`
}

/**
 * @summary Switches the currently displayed battlemap for all players in the session.
 */
export const patchApiGameSessionIdActiveMap = async (id: string,
    params?: PatchApiGameSessionIdActiveMapParams, options?: Parameters<typeof customInstance>[1]): Promise<patchApiGameSessionIdActiveMapResponse> => {

  return customInstance<patchApiGameSessionIdActiveMapResponse>(getPatchApiGameSessionIdActiveMapUrl(id,params),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getPatchApiGameSessionIdActiveMapMutationKey = () => ['patchApiGameSessionIdActiveMap'] as const;

export const getPatchApiGameSessionIdActiveMapMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiGameSessionIdActiveMap>>, TError,PatchApiGameSessionIdActiveMapMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiGameSessionIdActiveMap>>, TError,PatchApiGameSessionIdActiveMapMutationVariables, TContext> => {

const mutationKey = getPatchApiGameSessionIdActiveMapMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiGameSessionIdActiveMap>>, PatchApiGameSessionIdActiveMapMutationVariables> = (props) => {
          const {id,params} = props ?? {};

          return  patchApiGameSessionIdActiveMap(id,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiGameSessionIdActiveMapMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiGameSessionIdActiveMap>>>

    export type PatchApiGameSessionIdActiveMapMutationError = unknown
    export type PatchApiGameSessionIdActiveMapMutationVariables = {id: string;params?: PatchApiGameSessionIdActiveMapParams}

    /**
 * @summary Switches the currently displayed battlemap for all players in the session.
 */
export const usePatchApiGameSessionIdActiveMap = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiGameSessionIdActiveMap>>, TError,PatchApiGameSessionIdActiveMapMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiGameSessionIdActiveMap>>,
        TError,
        PatchApiGameSessionIdActiveMapMutationVariables,
        TContext
      > => {
      return useMutation(getPatchApiGameSessionIdActiveMapMutationOptions(options), queryClient);
    }
