/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateSessionDto,
  GameSessionDto,
  JoinSessionDto,
  PatchApiGameSessionIdActiveMapParams
} from '../../model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Creates a new game session with a generated 6-character room code.
 */
export const postApiGameSession = (
    createSessionDto?: CreateSessionDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GameSessionDto>> => {


    return axios.post(
      `/api/GameSession`,
      createSessionDto,options
    );
  }

export const getPostApiGameSessionUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/GameSession`,
    baseURL: '',


  });
}




export const getPostApiGameSessionMutationKey = () => ['postApiGameSession'] as const;

export const getPostApiGameSessionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGameSession>>, TError,PostApiGameSessionMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiGameSession>>, TError,PostApiGameSessionMutationVariables, TContext> => {

const mutationKey = getPostApiGameSessionMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiGameSession>>, PostApiGameSessionMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiGameSession(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiGameSessionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGameSession>>>
    export type PostApiGameSessionMutationBody = CreateSessionDto | undefined
    export type PostApiGameSessionMutationError = AxiosError<unknown>
    export type PostApiGameSessionMutationVariables = {data?: CreateSessionDto}

    /**
 * @summary Creates a new game session with a generated 6-character room code.
 */
export const usePostApiGameSession = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGameSession>>, TError,PostApiGameSessionMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiGameSession>>,
        TError,
        PostApiGameSessionMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiGameSessionMutationOptions(options), queryClient);
    }
    /**
 * @summary Retrieves a game session by its unique ID, including connected participants.
 */
export const getApiGameSessionId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GameSessionDto>> => {


    return axios.get(
      `/api/GameSession/${id}`,options
    );
  }

export const getGetApiGameSessionIdUrl = (id: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/GameSession/${id}`,
    baseURL: '',


  });
}




export const getGetApiGameSessionIdQueryKey = (id: string,) => {
    return [
    `/api/GameSession/${id}`
    ] as const;
    }


export const getGetApiGameSessionIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiGameSessionId>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGameSessionId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiGameSessionIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiGameSessionId>>> = ({ signal }) => getApiGameSessionId(id, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiGameSessionId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiGameSessionIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiGameSessionId>>>
export type GetApiGameSessionIdQueryError = AxiosError<unknown>


export function useGetApiGameSessionId<TData = Awaited<ReturnType<typeof getApiGameSessionId>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGameSessionId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGameSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiGameSessionId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiGameSessionId<TData = Awaited<ReturnType<typeof getApiGameSessionId>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGameSessionId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGameSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiGameSessionId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiGameSessionId<TData = Awaited<ReturnType<typeof getApiGameSessionId>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGameSessionId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves a game session by its unique ID, including connected participants.
 */

export function useGetApiGameSessionId<TData = Awaited<ReturnType<typeof getApiGameSessionId>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGameSessionId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiGameSessionIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Joins an existing game session using the 6-character room code.
 */
export const postApiGameSessionJoin = (
    joinSessionDto?: JoinSessionDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GameSessionDto>> => {


    return axios.post(
      `/api/GameSession/join`,
      joinSessionDto,options
    );
  }

export const getPostApiGameSessionJoinUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/GameSession/join`,
    baseURL: '',


  });
}




export const getPostApiGameSessionJoinMutationKey = () => ['postApiGameSessionJoin'] as const;

export const getPostApiGameSessionJoinMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGameSessionJoin>>, TError,PostApiGameSessionJoinMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiGameSessionJoin>>, TError,PostApiGameSessionJoinMutationVariables, TContext> => {

const mutationKey = getPostApiGameSessionJoinMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiGameSessionJoin>>, PostApiGameSessionJoinMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiGameSessionJoin(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiGameSessionJoinMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGameSessionJoin>>>
    export type PostApiGameSessionJoinMutationBody = JoinSessionDto | undefined
    export type PostApiGameSessionJoinMutationError = AxiosError<unknown>
    export type PostApiGameSessionJoinMutationVariables = {data?: JoinSessionDto}

    /**
 * @summary Joins an existing game session using the 6-character room code.
 */
export const usePostApiGameSessionJoin = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGameSessionJoin>>, TError,PostApiGameSessionJoinMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiGameSessionJoin>>,
        TError,
        PostApiGameSessionJoinMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiGameSessionJoinMutationOptions(options), queryClient);
    }
    export const postApiGameSessionSessionIdAddMapMapId = (
    sessionId: string,
    mapId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.post(
      `/api/GameSession/${sessionId}/add-map/${mapId}`,
      undefined,options
    );
  }

export const getPostApiGameSessionSessionIdAddMapMapIdUrl = (sessionId: string,
    mapId: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/GameSession/${sessionId}/add-map/${mapId}`,
    baseURL: '',


  });
}




export const getPostApiGameSessionSessionIdAddMapMapIdMutationKey = () => ['postApiGameSessionSessionIdAddMapMapId'] as const;

export const getPostApiGameSessionSessionIdAddMapMapIdMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGameSessionSessionIdAddMapMapId>>, TError,PostApiGameSessionSessionIdAddMapMapIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiGameSessionSessionIdAddMapMapId>>, TError,PostApiGameSessionSessionIdAddMapMapIdMutationVariables, TContext> => {

const mutationKey = getPostApiGameSessionSessionIdAddMapMapIdMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiGameSessionSessionIdAddMapMapId>>, PostApiGameSessionSessionIdAddMapMapIdMutationVariables> = (props) => {
          const {sessionId,mapId} = props ?? {};

          return  postApiGameSessionSessionIdAddMapMapId(sessionId,mapId,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiGameSessionSessionIdAddMapMapIdMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGameSessionSessionIdAddMapMapId>>>

    export type PostApiGameSessionSessionIdAddMapMapIdMutationError = AxiosError<unknown>
    export type PostApiGameSessionSessionIdAddMapMapIdMutationVariables = {sessionId: string;mapId: string}

    export const usePostApiGameSessionSessionIdAddMapMapId = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGameSessionSessionIdAddMapMapId>>, TError,PostApiGameSessionSessionIdAddMapMapIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiGameSessionSessionIdAddMapMapId>>,
        TError,
        PostApiGameSessionSessionIdAddMapMapIdMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiGameSessionSessionIdAddMapMapIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Switches the currently displayed battlemap for all players in the session.
 */
export const patchApiGameSessionIdActiveMap = (
    id: string,
    params?: PatchApiGameSessionIdActiveMapParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.patch(
      `/api/GameSession/${id}/active-map`,
      undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getPatchApiGameSessionIdActiveMapUrl = (id: string,
    params?: PatchApiGameSessionIdActiveMapParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/GameSession/${id}/active-map`,
    baseURL: '',
    params,

  });
}




export const getPatchApiGameSessionIdActiveMapMutationKey = () => ['patchApiGameSessionIdActiveMap'] as const;

export const getPatchApiGameSessionIdActiveMapMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiGameSessionIdActiveMap>>, TError,PatchApiGameSessionIdActiveMapMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiGameSessionIdActiveMap>>, TError,PatchApiGameSessionIdActiveMapMutationVariables, TContext> => {

const mutationKey = getPatchApiGameSessionIdActiveMapMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiGameSessionIdActiveMap>>, PatchApiGameSessionIdActiveMapMutationVariables> = (props) => {
          const {id,params} = props ?? {};

          return  patchApiGameSessionIdActiveMap(id,params,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiGameSessionIdActiveMapMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiGameSessionIdActiveMap>>>

    export type PatchApiGameSessionIdActiveMapMutationError = AxiosError<unknown>
    export type PatchApiGameSessionIdActiveMapMutationVariables = {id: string;params?: PatchApiGameSessionIdActiveMapParams}

    /**
 * @summary Switches the currently displayed battlemap for all players in the session.
 */
export const usePatchApiGameSessionIdActiveMap = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiGameSessionIdActiveMap>>, TError,PatchApiGameSessionIdActiveMapMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiGameSessionIdActiveMap>>,
        TError,
        PatchApiGameSessionIdActiveMapMutationVariables,
        TContext
      > => {
      return useMutation(getPatchApiGameSessionIdActiveMapMutationOptions(options), queryClient);
    }
