/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GridDto,
  PutApiGridMapMapIdParams,
  UpdateGridDto
} from '../../model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Retrieves the current grid configuration for a given battlemap.
 */
export const getApiGridMapMapId = (
    mapId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GridDto>> => {


    return axios.get(
      `/api/Grid/map/${mapId}`,options
    );
  }

export const getGetApiGridMapMapIdUrl = (mapId: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Grid/map/${mapId}`,
    baseURL: '',


  });
}




export const getGetApiGridMapMapIdQueryKey = (mapId: string,) => {
    return [
    `/api/Grid/map/${mapId}`
    ] as const;
    }


export const getGetApiGridMapMapIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiGridMapMapId>>, TError = AxiosError<unknown>>(mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGridMapMapId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiGridMapMapIdQueryKey(mapId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiGridMapMapId>>> = ({ signal }) => getApiGridMapMapId(mapId, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: mapId !== null && mapId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiGridMapMapId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiGridMapMapIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiGridMapMapId>>>
export type GetApiGridMapMapIdQueryError = AxiosError<unknown>


export function useGetApiGridMapMapId<TData = Awaited<ReturnType<typeof getApiGridMapMapId>>, TError = AxiosError<unknown>>(
 mapId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGridMapMapId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGridMapMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiGridMapMapId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiGridMapMapId<TData = Awaited<ReturnType<typeof getApiGridMapMapId>>, TError = AxiosError<unknown>>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGridMapMapId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGridMapMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiGridMapMapId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiGridMapMapId<TData = Awaited<ReturnType<typeof getApiGridMapMapId>>, TError = AxiosError<unknown>>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGridMapMapId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves the current grid configuration for a given battlemap.
 */

export function useGetApiGridMapMapId<TData = Awaited<ReturnType<typeof getApiGridMapMapId>>, TError = AxiosError<unknown>>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGridMapMapId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiGridMapMapIdQueryOptions(mapId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Updates the grid dimensions, cell size, and offsets for a battlemap.
 */
export const putApiGridMapMapId = (
    mapId: string,
    updateGridDto?: UpdateGridDto,
    params?: PutApiGridMapMapIdParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GridDto>> => {


    return axios.put(
      `/api/Grid/map/${mapId}`,
      updateGridDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getPutApiGridMapMapIdUrl = (mapId: string,
    params?: PutApiGridMapMapIdParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Grid/map/${mapId}`,
    baseURL: '',
    params,

  });
}




export const getPutApiGridMapMapIdMutationKey = () => ['putApiGridMapMapId'] as const;

export const getPutApiGridMapMapIdMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiGridMapMapId>>, TError,PutApiGridMapMapIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiGridMapMapId>>, TError,PutApiGridMapMapIdMutationVariables, TContext> => {

const mutationKey = getPutApiGridMapMapIdMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiGridMapMapId>>, PutApiGridMapMapIdMutationVariables> = (props) => {
          const {mapId,data,params} = props ?? {};

          return  putApiGridMapMapId(mapId,data,params,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiGridMapMapIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiGridMapMapId>>>
    export type PutApiGridMapMapIdMutationBody = UpdateGridDto | undefined
    export type PutApiGridMapMapIdMutationError = AxiosError<unknown>
    export type PutApiGridMapMapIdMutationVariables = {mapId: string;data?: UpdateGridDto;params?: PutApiGridMapMapIdParams}

    /**
 * @summary Updates the grid dimensions, cell size, and offsets for a battlemap.
 */
export const usePutApiGridMapMapId = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiGridMapMapId>>, TError,PutApiGridMapMapIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiGridMapMapId>>,
        TError,
        PutApiGridMapMapIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiGridMapMapIdMutationOptions(options), queryClient);
    }
