/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GridDto,
  PutApiGridMapMapIdParams,
  UpdateGridDto
} from '../../model';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiGridMapMapIdResponse200TextPlain = {
  data: GridDto
  status: 200
}

export type getApiGridMapMapIdResponse200ApplicationJson = {
  data: GridDto
  status: 200
}

export type getApiGridMapMapIdResponse200TextJson = {
  data: GridDto
  status: 200
}

export type getApiGridMapMapIdResponseSuccess = (getApiGridMapMapIdResponse200TextPlain | getApiGridMapMapIdResponse200ApplicationJson | getApiGridMapMapIdResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiGridMapMapIdResponse = (getApiGridMapMapIdResponseSuccess)

export const getGetApiGridMapMapIdUrl = (mapId: string,) => {




  return `/api/Grid/map/${mapId}`
}

/**
 * @summary Retrieves the current grid configuration for a given battlemap.
 */
export const getApiGridMapMapId = async (mapId: string, options?: Parameters<typeof customInstance>[1]): Promise<getApiGridMapMapIdResponse> => {

  return customInstance<getApiGridMapMapIdResponse>(getGetApiGridMapMapIdUrl(mapId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiGridMapMapIdQueryKey = (mapId: string,) => {
    return [
    `/api/Grid/map/${mapId}`
    ] as const;
    }


export const getGetApiGridMapMapIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiGridMapMapId>>, TError = unknown>(mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGridMapMapId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiGridMapMapIdQueryKey(mapId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiGridMapMapId>>> = ({ signal }) => getApiGridMapMapId(mapId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: mapId !== null && mapId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiGridMapMapId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiGridMapMapIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiGridMapMapId>>>
export type GetApiGridMapMapIdQueryError = unknown


export function useGetApiGridMapMapId<TData = Awaited<ReturnType<typeof getApiGridMapMapId>>, TError = unknown>(
 mapId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGridMapMapId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGridMapMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiGridMapMapId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiGridMapMapId<TData = Awaited<ReturnType<typeof getApiGridMapMapId>>, TError = unknown>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGridMapMapId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGridMapMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiGridMapMapId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiGridMapMapId<TData = Awaited<ReturnType<typeof getApiGridMapMapId>>, TError = unknown>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGridMapMapId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves the current grid configuration for a given battlemap.
 */

export function useGetApiGridMapMapId<TData = Awaited<ReturnType<typeof getApiGridMapMapId>>, TError = unknown>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGridMapMapId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiGridMapMapIdQueryOptions(mapId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putApiGridMapMapIdResponse200TextPlain = {
  data: GridDto
  status: 200
}

export type putApiGridMapMapIdResponse200ApplicationJson = {
  data: GridDto
  status: 200
}

export type putApiGridMapMapIdResponse200TextJson = {
  data: GridDto
  status: 200
}

export type putApiGridMapMapIdResponseSuccess = (putApiGridMapMapIdResponse200TextPlain | putApiGridMapMapIdResponse200ApplicationJson | putApiGridMapMapIdResponse200TextJson) & {
  headers: Headers;
};
;

export type putApiGridMapMapIdResponse = (putApiGridMapMapIdResponseSuccess)

export const getPutApiGridMapMapIdUrl = (mapId: string,
    params?: PutApiGridMapMapIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Grid/map/${mapId}?${stringifiedParams}` : `/api/Grid/map/${mapId}`
}

/**
 * @summary Updates the grid dimensions, cell size, and offsets for a battlemap.
 */
export const putApiGridMapMapId = async (mapId: string,
    updateGridDto?: UpdateGridDto,
    params?: PutApiGridMapMapIdParams, options?: Parameters<typeof customInstance>[1]): Promise<putApiGridMapMapIdResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<putApiGridMapMapIdResponse>(getPutApiGridMapMapIdUrl(mapId,params),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateGridDto)
  }
);}





export const getPutApiGridMapMapIdMutationKey = () => ['putApiGridMapMapId'] as const;

export const getPutApiGridMapMapIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiGridMapMapId>>, TError,PutApiGridMapMapIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiGridMapMapId>>, TError,PutApiGridMapMapIdMutationVariables, TContext> => {

const mutationKey = getPutApiGridMapMapIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiGridMapMapId>>, PutApiGridMapMapIdMutationVariables> = (props) => {
          const {mapId,data,params} = props ?? {};

          return  putApiGridMapMapId(mapId,data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiGridMapMapIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiGridMapMapId>>>
    export type PutApiGridMapMapIdMutationBody = UpdateGridDto | undefined
    export type PutApiGridMapMapIdMutationError = unknown
    export type PutApiGridMapMapIdMutationVariables = {mapId: string;data?: UpdateGridDto;params?: PutApiGridMapMapIdParams}

    /**
 * @summary Updates the grid dimensions, cell size, and offsets for a battlemap.
 */
export const usePutApiGridMapMapId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiGridMapMapId>>, TError,PutApiGridMapMapIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiGridMapMapId>>,
        TError,
        PutApiGridMapMapIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiGridMapMapIdMutationOptions(options), queryClient);
    }
