/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MapDetailDto,
  MapSummaryDto,
  PostApiMapBody
} from '../../model';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiMapResponse200TextPlain = {
  data: MapSummaryDto[]
  status: 200
}

export type getApiMapResponse200ApplicationJson = {
  data: MapSummaryDto[]
  status: 200
}

export type getApiMapResponse200TextJson = {
  data: MapSummaryDto[]
  status: 200
}

export type getApiMapResponseSuccess = (getApiMapResponse200TextPlain | getApiMapResponse200ApplicationJson | getApiMapResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiMapResponse = (getApiMapResponseSuccess)

export const getGetApiMapUrl = () => {




  return `/api/Map`
}

/**
 * @summary Retrieves a list of all uploaded maps (summary metadata).
 */
export const getApiMap = async ( options?: Parameters<typeof customInstance>[1]): Promise<getApiMapResponse> => {

  return customInstance<getApiMapResponse>(getGetApiMapUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiMapQueryKey = () => {
    return [
    `/api/Map`
    ] as const;
    }


export const getGetApiMapQueryOptions = <TData = Awaited<ReturnType<typeof getApiMap>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMap>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMapQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMap>>> = ({ signal }) => getApiMap({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMap>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMapQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMap>>>
export type GetApiMapQueryError = unknown


export function useGetApiMap<TData = Awaited<ReturnType<typeof getApiMap>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMap>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMap>>,
          TError,
          Awaited<ReturnType<typeof getApiMap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMap<TData = Awaited<ReturnType<typeof getApiMap>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMap>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMap>>,
          TError,
          Awaited<ReturnType<typeof getApiMap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMap<TData = Awaited<ReturnType<typeof getApiMap>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMap>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves a list of all uploaded maps (summary metadata).
 */

export function useGetApiMap<TData = Awaited<ReturnType<typeof getApiMap>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMap>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMapQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiMapResponse200TextPlain = {
  data: MapDetailDto
  status: 200
}

export type postApiMapResponse200ApplicationJson = {
  data: MapDetailDto
  status: 200
}

export type postApiMapResponse200TextJson = {
  data: MapDetailDto
  status: 200
}

export type postApiMapResponseSuccess = (postApiMapResponse200TextPlain | postApiMapResponse200ApplicationJson | postApiMapResponse200TextJson) & {
  headers: Headers;
};
;

export type postApiMapResponse = (postApiMapResponseSuccess)

export const getPostApiMapUrl = () => {




  return `/api/Map`
}

/**
 * @summary Uploads a new battlemap image file and generates its default grid configuration.
 */
export const postApiMap = async (postApiMapBody?: PostApiMapBody, options?: Parameters<typeof customInstance>[1]): Promise<postApiMapResponse> => {
    const formData = new FormData();
if(postApiMapBody?.Title !== undefined) {
 formData.append(`Title`, postApiMapBody.Title);
 }
if(postApiMapBody?.InitialCellSize !== undefined) {
 formData.append(`InitialCellSize`, postApiMapBody.InitialCellSize.toString())
 }
if(postApiMapBody?.image !== undefined) {
 formData.append(`image`, postApiMapBody.image);
 }

  return customInstance<postApiMapResponse>(getPostApiMapUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}





export const getPostApiMapMutationKey = () => ['postApiMap'] as const;

export const getPostApiMapMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMap>>, TError,PostApiMapMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiMap>>, TError,PostApiMapMutationVariables, TContext> => {

const mutationKey = getPostApiMapMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiMap>>, PostApiMapMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiMap(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiMapMutationResult = NonNullable<Awaited<ReturnType<typeof postApiMap>>>
    export type PostApiMapMutationBody = PostApiMapBody | undefined
    export type PostApiMapMutationError = unknown
    export type PostApiMapMutationVariables = {data?: PostApiMapBody}

    /**
 * @summary Uploads a new battlemap image file and generates its default grid configuration.
 */
export const usePostApiMap = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMap>>, TError,PostApiMapMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiMap>>,
        TError,
        PostApiMapMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiMapMutationOptions(options), queryClient);
    }
    export type getApiMapIdResponse200TextPlain = {
  data: MapDetailDto
  status: 200
}

export type getApiMapIdResponse200ApplicationJson = {
  data: MapDetailDto
  status: 200
}

export type getApiMapIdResponse200TextJson = {
  data: MapDetailDto
  status: 200
}

export type getApiMapIdResponseSuccess = (getApiMapIdResponse200TextPlain | getApiMapIdResponse200ApplicationJson | getApiMapIdResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiMapIdResponse = (getApiMapIdResponseSuccess)

export const getGetApiMapIdUrl = (id: string,) => {




  return `/api/Map/${id}`
}

/**
 * @summary Retrieves full map details including its grid, tokens, and active spells.
 */
export const getApiMapId = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<getApiMapIdResponse> => {

  return customInstance<getApiMapIdResponse>(getGetApiMapIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiMapIdQueryKey = (id: string,) => {
    return [
    `/api/Map/${id}`
    ] as const;
    }


export const getGetApiMapIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiMapId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMapIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMapId>>> = ({ signal }) => getApiMapId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMapId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMapIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMapId>>>
export type GetApiMapIdQueryError = unknown


export function useGetApiMapId<TData = Awaited<ReturnType<typeof getApiMapId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiMapId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMapId<TData = Awaited<ReturnType<typeof getApiMapId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiMapId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMapId<TData = Awaited<ReturnType<typeof getApiMapId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves full map details including its grid, tokens, and active spells.
 */

export function useGetApiMapId<TData = Awaited<ReturnType<typeof getApiMapId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMapIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteApiMapIdResponse200 = {
  data: void
  status: 200
}

export type deleteApiMapIdResponseSuccess = (deleteApiMapIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiMapIdResponse = (deleteApiMapIdResponseSuccess)

export const getDeleteApiMapIdUrl = (id: string,) => {




  return `/api/Map/${id}`
}

/**
 * @summary Deletes a battlemap and cascades the removal of its grid, tokens, and spells.
 */
export const deleteApiMapId = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<deleteApiMapIdResponse> => {

  return customInstance<deleteApiMapIdResponse>(getDeleteApiMapIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiMapIdMutationKey = () => ['deleteApiMapId'] as const;

export const getDeleteApiMapIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMapId>>, TError,DeleteApiMapIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiMapId>>, TError,DeleteApiMapIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiMapIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiMapId>>, DeleteApiMapIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteApiMapId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiMapIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiMapId>>>

    export type DeleteApiMapIdMutationError = unknown
    export type DeleteApiMapIdMutationVariables = {id: string}

    /**
 * @summary Deletes a battlemap and cascades the removal of its grid, tokens, and spells.
 */
export const useDeleteApiMapId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMapId>>, TError,DeleteApiMapIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiMapId>>,
        TError,
        DeleteApiMapIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiMapIdMutationOptions(options), queryClient);
    }
