/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  MapDetailDto,
  MapSummaryDto,
  PostApiMapBody
} from '../../model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Retrieves a list of all uploaded maps (summary metadata).
 */
export const getApiMap = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MapSummaryDto[]>> => {


    return axios.get(
      `/api/Map`,options
    );
  }

export const getGetApiMapUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Map`,
    baseURL: '',


  });
}




export const getGetApiMapQueryKey = () => {
    return [
    `/api/Map`
    ] as const;
    }


export const getGetApiMapQueryOptions = <TData = Awaited<ReturnType<typeof getApiMap>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMap>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMapQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMap>>> = ({ signal }) => getApiMap({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMap>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMapQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMap>>>
export type GetApiMapQueryError = AxiosError<unknown>


export function useGetApiMap<TData = Awaited<ReturnType<typeof getApiMap>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMap>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMap>>,
          TError,
          Awaited<ReturnType<typeof getApiMap>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMap<TData = Awaited<ReturnType<typeof getApiMap>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMap>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMap>>,
          TError,
          Awaited<ReturnType<typeof getApiMap>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMap<TData = Awaited<ReturnType<typeof getApiMap>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMap>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves a list of all uploaded maps (summary metadata).
 */

export function useGetApiMap<TData = Awaited<ReturnType<typeof getApiMap>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMap>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMapQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Uploads a new battlemap image file and generates its default grid configuration.
 */
export const postApiMap = (
    postApiMapBody?: PostApiMapBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MapDetailDto>> => {

    const formData = new FormData();
if(postApiMapBody?.Title !== undefined) {
 formData.append(`Title`, postApiMapBody.Title);
 }
if(postApiMapBody?.InitialCellSize !== undefined) {
 formData.append(`InitialCellSize`, postApiMapBody.InitialCellSize.toString())
 }
if(postApiMapBody?.image !== undefined) {
 formData.append(`image`, postApiMapBody.image);
 }

    return axios.post(
      `/api/Map`,
      formData,options
    );
  }

export const getPostApiMapUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Map`,
    baseURL: '',


  });
}




export const getPostApiMapMutationKey = () => ['postApiMap'] as const;

export const getPostApiMapMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMap>>, TError,PostApiMapMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiMap>>, TError,PostApiMapMutationVariables, TContext> => {

const mutationKey = getPostApiMapMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiMap>>, PostApiMapMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiMap(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiMapMutationResult = NonNullable<Awaited<ReturnType<typeof postApiMap>>>
    export type PostApiMapMutationBody = PostApiMapBody | undefined
    export type PostApiMapMutationError = AxiosError<unknown>
    export type PostApiMapMutationVariables = {data?: PostApiMapBody}

    /**
 * @summary Uploads a new battlemap image file and generates its default grid configuration.
 */
export const usePostApiMap = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMap>>, TError,PostApiMapMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiMap>>,
        TError,
        PostApiMapMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiMapMutationOptions(options), queryClient);
    }
    /**
 * @summary Retrieves full map details including its grid, tokens, and active spells.
 */
export const getApiMapId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MapDetailDto>> => {


    return axios.get(
      `/api/Map/${id}`,options
    );
  }

export const getGetApiMapIdUrl = (id: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Map/${id}`,
    baseURL: '',


  });
}




export const getGetApiMapIdQueryKey = (id: string,) => {
    return [
    `/api/Map/${id}`
    ] as const;
    }


export const getGetApiMapIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiMapId>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMapIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMapId>>> = ({ signal }) => getApiMapId(id, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMapId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMapIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMapId>>>
export type GetApiMapIdQueryError = AxiosError<unknown>


export function useGetApiMapId<TData = Awaited<ReturnType<typeof getApiMapId>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiMapId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMapId<TData = Awaited<ReturnType<typeof getApiMapId>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiMapId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMapId<TData = Awaited<ReturnType<typeof getApiMapId>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves full map details including its grid, tokens, and active spells.
 */

export function useGetApiMapId<TData = Awaited<ReturnType<typeof getApiMapId>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMapIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Deletes a battlemap and cascades the removal of its grid, tokens, and spells.
 */
export const deleteApiMapId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.delete(
      `/api/Map/${id}`,options
    );
  }

export const getDeleteApiMapIdUrl = (id: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Map/${id}`,
    baseURL: '',


  });
}




export const getDeleteApiMapIdMutationKey = () => ['deleteApiMapId'] as const;

export const getDeleteApiMapIdMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMapId>>, TError,DeleteApiMapIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiMapId>>, TError,DeleteApiMapIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiMapIdMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiMapId>>, DeleteApiMapIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteApiMapId(id,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiMapIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiMapId>>>

    export type DeleteApiMapIdMutationError = AxiosError<unknown>
    export type DeleteApiMapIdMutationVariables = {id: string}

    /**
 * @summary Deletes a battlemap and cascades the removal of its grid, tokens, and spells.
 */
export const useDeleteApiMapId = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMapId>>, TError,DeleteApiMapIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiMapId>>,
        TError,
        DeleteApiMapIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiMapIdMutationOptions(options), queryClient);
    }
