/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CharacterDto,
  CreateCharacterDto,
  UpdateCharacterSheetDto
} from '../../model';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiCharacterSessionSessionIdResponse200TextPlain = {
  data: CharacterDto[]
  status: 200
}

export type getApiCharacterSessionSessionIdResponse200ApplicationJson = {
  data: CharacterDto[]
  status: 200
}

export type getApiCharacterSessionSessionIdResponse200TextJson = {
  data: CharacterDto[]
  status: 200
}

export type getApiCharacterSessionSessionIdResponseSuccess = (getApiCharacterSessionSessionIdResponse200TextPlain | getApiCharacterSessionSessionIdResponse200ApplicationJson | getApiCharacterSessionSessionIdResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiCharacterSessionSessionIdResponse = (getApiCharacterSessionSessionIdResponseSuccess)

export const getGetApiCharacterSessionSessionIdUrl = (sessionId: string,) => {




  return `/api/Character/session/${sessionId}`
}

/**
 * @summary Retrieves all characters created within a specific game session.
 */
export const getApiCharacterSessionSessionId = async (sessionId: string, options?: Parameters<typeof customInstance>[1]): Promise<getApiCharacterSessionSessionIdResponse> => {

  return customInstance<getApiCharacterSessionSessionIdResponse>(getGetApiCharacterSessionSessionIdUrl(sessionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiCharacterSessionSessionIdQueryKey = (sessionId: string,) => {
    return [
    `/api/Character/session/${sessionId}`
    ] as const;
    }


export const getGetApiCharacterSessionSessionIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError = unknown>(sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCharacterSessionSessionIdQueryKey(sessionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>> = ({ signal }) => getApiCharacterSessionSessionId(sessionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: sessionId !== null && sessionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCharacterSessionSessionIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>>
export type GetApiCharacterSessionSessionIdQueryError = unknown


export function useGetApiCharacterSessionSessionId<TData = Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError = unknown>(
 sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCharacterSessionSessionId<TData = Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError = unknown>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCharacterSessionSessionId<TData = Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError = unknown>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves all characters created within a specific game session.
 */

export function useGetApiCharacterSessionSessionId<TData = Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError = unknown>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCharacterSessionSessionIdQueryOptions(sessionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiCharacterIdResponse200TextPlain = {
  data: CharacterDto
  status: 200
}

export type getApiCharacterIdResponse200ApplicationJson = {
  data: CharacterDto
  status: 200
}

export type getApiCharacterIdResponse200TextJson = {
  data: CharacterDto
  status: 200
}

export type getApiCharacterIdResponseSuccess = (getApiCharacterIdResponse200TextPlain | getApiCharacterIdResponse200ApplicationJson | getApiCharacterIdResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiCharacterIdResponse = (getApiCharacterIdResponseSuccess)

export const getGetApiCharacterIdUrl = (id: string,) => {




  return `/api/Character/${id}`
}

/**
 * @summary Retrieves a character sheet by its unique identifier.
 */
export const getApiCharacterId = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<getApiCharacterIdResponse> => {

  return customInstance<getApiCharacterIdResponse>(getGetApiCharacterIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiCharacterIdQueryKey = (id: string,) => {
    return [
    `/api/Character/${id}`
    ] as const;
    }


export const getGetApiCharacterIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCharacterId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCharacterIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCharacterId>>> = ({ signal }) => getApiCharacterId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCharacterIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCharacterId>>>
export type GetApiCharacterIdQueryError = unknown


export function useGetApiCharacterId<TData = Awaited<ReturnType<typeof getApiCharacterId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCharacterId>>,
          TError,
          Awaited<ReturnType<typeof getApiCharacterId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCharacterId<TData = Awaited<ReturnType<typeof getApiCharacterId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCharacterId>>,
          TError,
          Awaited<ReturnType<typeof getApiCharacterId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCharacterId<TData = Awaited<ReturnType<typeof getApiCharacterId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves a character sheet by its unique identifier.
 */

export function useGetApiCharacterId<TData = Awaited<ReturnType<typeof getApiCharacterId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCharacterIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putApiCharacterIdResponse200TextPlain = {
  data: CharacterDto
  status: 200
}

export type putApiCharacterIdResponse200ApplicationJson = {
  data: CharacterDto
  status: 200
}

export type putApiCharacterIdResponse200TextJson = {
  data: CharacterDto
  status: 200
}

export type putApiCharacterIdResponseSuccess = (putApiCharacterIdResponse200TextPlain | putApiCharacterIdResponse200ApplicationJson | putApiCharacterIdResponse200TextJson) & {
  headers: Headers;
};
;

export type putApiCharacterIdResponse = (putApiCharacterIdResponseSuccess)

export const getPutApiCharacterIdUrl = (id: string,) => {




  return `/api/Character/${id}`
}

/**
 * @summary Updates an existing character sheet (e.g., stats, Max HP, AC).
 */
export const putApiCharacterId = async (id: string,
    updateCharacterSheetDto?: UpdateCharacterSheetDto, options?: Parameters<typeof customInstance>[1]): Promise<putApiCharacterIdResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<putApiCharacterIdResponse>(getPutApiCharacterIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateCharacterSheetDto)
  }
);}





export const getPutApiCharacterIdMutationKey = () => ['putApiCharacterId'] as const;

export const getPutApiCharacterIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCharacterId>>, TError,PutApiCharacterIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiCharacterId>>, TError,PutApiCharacterIdMutationVariables, TContext> => {

const mutationKey = getPutApiCharacterIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiCharacterId>>, PutApiCharacterIdMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putApiCharacterId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiCharacterIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiCharacterId>>>
    export type PutApiCharacterIdMutationBody = UpdateCharacterSheetDto | undefined
    export type PutApiCharacterIdMutationError = unknown
    export type PutApiCharacterIdMutationVariables = {id: string;data?: UpdateCharacterSheetDto}

    /**
 * @summary Updates an existing character sheet (e.g., stats, Max HP, AC).
 */
export const usePutApiCharacterId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCharacterId>>, TError,PutApiCharacterIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiCharacterId>>,
        TError,
        PutApiCharacterIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiCharacterIdMutationOptions(options), queryClient);
    }
    export type deleteApiCharacterIdResponse200 = {
  data: void
  status: 200
}

export type deleteApiCharacterIdResponseSuccess = (deleteApiCharacterIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiCharacterIdResponse = (deleteApiCharacterIdResponseSuccess)

export const getDeleteApiCharacterIdUrl = (id: string,) => {




  return `/api/Character/${id}`
}

/**
 * @summary Permanently deletes a character from the campaign.
 */
export const deleteApiCharacterId = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<deleteApiCharacterIdResponse> => {

  return customInstance<deleteApiCharacterIdResponse>(getDeleteApiCharacterIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiCharacterIdMutationKey = () => ['deleteApiCharacterId'] as const;

export const getDeleteApiCharacterIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCharacterId>>, TError,DeleteApiCharacterIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCharacterId>>, TError,DeleteApiCharacterIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiCharacterIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCharacterId>>, DeleteApiCharacterIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteApiCharacterId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiCharacterIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCharacterId>>>

    export type DeleteApiCharacterIdMutationError = unknown
    export type DeleteApiCharacterIdMutationVariables = {id: string}

    /**
 * @summary Permanently deletes a character from the campaign.
 */
export const useDeleteApiCharacterId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCharacterId>>, TError,DeleteApiCharacterIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiCharacterId>>,
        TError,
        DeleteApiCharacterIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiCharacterIdMutationOptions(options), queryClient);
    }
    export type postApiCharacterResponse200TextPlain = {
  data: CharacterDto
  status: 200
}

export type postApiCharacterResponse200ApplicationJson = {
  data: CharacterDto
  status: 200
}

export type postApiCharacterResponse200TextJson = {
  data: CharacterDto
  status: 200
}

export type postApiCharacterResponseSuccess = (postApiCharacterResponse200TextPlain | postApiCharacterResponse200ApplicationJson | postApiCharacterResponse200TextJson) & {
  headers: Headers;
};
;

export type postApiCharacterResponse = (postApiCharacterResponseSuccess)

export const getPostApiCharacterUrl = () => {




  return `/api/Character`
}

/**
 * @summary Creates a new character for a game session.
 */
export const postApiCharacter = async (createCharacterDto?: CreateCharacterDto, options?: Parameters<typeof customInstance>[1]): Promise<postApiCharacterResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<postApiCharacterResponse>(getPostApiCharacterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createCharacterDto)
  }
);}





export const getPostApiCharacterMutationKey = () => ['postApiCharacter'] as const;

export const getPostApiCharacterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCharacter>>, TError,PostApiCharacterMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiCharacter>>, TError,PostApiCharacterMutationVariables, TContext> => {

const mutationKey = getPostApiCharacterMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCharacter>>, PostApiCharacterMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiCharacter(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCharacterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCharacter>>>
    export type PostApiCharacterMutationBody = CreateCharacterDto | undefined
    export type PostApiCharacterMutationError = unknown
    export type PostApiCharacterMutationVariables = {data?: CreateCharacterDto}

    /**
 * @summary Creates a new character for a game session.
 */
export const usePostApiCharacter = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCharacter>>, TError,PostApiCharacterMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCharacter>>,
        TError,
        PostApiCharacterMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiCharacterMutationOptions(options), queryClient);
    }
