/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CharacterDto,
  CreateCharacterDto,
  UpdateCharacterSheetDto
} from '../../model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Retrieves all characters created within a specific game session.
 */
export const getApiCharacterSessionSessionId = (
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CharacterDto[]>> => {


    return axios.get(
      `/api/Character/session/${sessionId}`,options
    );
  }

export const getGetApiCharacterSessionSessionIdUrl = (sessionId: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Character/session/${sessionId}`,
    baseURL: '',


  });
}




export const getGetApiCharacterSessionSessionIdQueryKey = (sessionId: string,) => {
    return [
    `/api/Character/session/${sessionId}`
    ] as const;
    }


export const getGetApiCharacterSessionSessionIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError = AxiosError<unknown>>(sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCharacterSessionSessionIdQueryKey(sessionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>> = ({ signal }) => getApiCharacterSessionSessionId(sessionId, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: sessionId !== null && sessionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCharacterSessionSessionIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>>
export type GetApiCharacterSessionSessionIdQueryError = AxiosError<unknown>


export function useGetApiCharacterSessionSessionId<TData = Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError = AxiosError<unknown>>(
 sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCharacterSessionSessionId<TData = Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError = AxiosError<unknown>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCharacterSessionSessionId<TData = Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError = AxiosError<unknown>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves all characters created within a specific game session.
 */

export function useGetApiCharacterSessionSessionId<TData = Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError = AxiosError<unknown>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterSessionSessionId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCharacterSessionSessionIdQueryOptions(sessionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Retrieves a character sheet by its unique identifier.
 */
export const getApiCharacterId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CharacterDto>> => {


    return axios.get(
      `/api/Character/${id}`,options
    );
  }

export const getGetApiCharacterIdUrl = (id: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Character/${id}`,
    baseURL: '',


  });
}




export const getGetApiCharacterIdQueryKey = (id: string,) => {
    return [
    `/api/Character/${id}`
    ] as const;
    }


export const getGetApiCharacterIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCharacterId>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCharacterIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCharacterId>>> = ({ signal }) => getApiCharacterId(id, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCharacterIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCharacterId>>>
export type GetApiCharacterIdQueryError = AxiosError<unknown>


export function useGetApiCharacterId<TData = Awaited<ReturnType<typeof getApiCharacterId>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCharacterId>>,
          TError,
          Awaited<ReturnType<typeof getApiCharacterId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCharacterId<TData = Awaited<ReturnType<typeof getApiCharacterId>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCharacterId>>,
          TError,
          Awaited<ReturnType<typeof getApiCharacterId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCharacterId<TData = Awaited<ReturnType<typeof getApiCharacterId>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves a character sheet by its unique identifier.
 */

export function useGetApiCharacterId<TData = Awaited<ReturnType<typeof getApiCharacterId>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCharacterId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCharacterIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Updates an existing character sheet (e.g., stats, Max HP, AC).
 */
export const putApiCharacterId = (
    id: string,
    updateCharacterSheetDto?: UpdateCharacterSheetDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CharacterDto>> => {


    return axios.put(
      `/api/Character/${id}`,
      updateCharacterSheetDto,options
    );
  }

export const getPutApiCharacterIdUrl = (id: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Character/${id}`,
    baseURL: '',


  });
}




export const getPutApiCharacterIdMutationKey = () => ['putApiCharacterId'] as const;

export const getPutApiCharacterIdMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCharacterId>>, TError,PutApiCharacterIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiCharacterId>>, TError,PutApiCharacterIdMutationVariables, TContext> => {

const mutationKey = getPutApiCharacterIdMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiCharacterId>>, PutApiCharacterIdMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putApiCharacterId(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiCharacterIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiCharacterId>>>
    export type PutApiCharacterIdMutationBody = UpdateCharacterSheetDto | undefined
    export type PutApiCharacterIdMutationError = AxiosError<unknown>
    export type PutApiCharacterIdMutationVariables = {id: string;data?: UpdateCharacterSheetDto}

    /**
 * @summary Updates an existing character sheet (e.g., stats, Max HP, AC).
 */
export const usePutApiCharacterId = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCharacterId>>, TError,PutApiCharacterIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiCharacterId>>,
        TError,
        PutApiCharacterIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiCharacterIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Permanently deletes a character from the campaign.
 */
export const deleteApiCharacterId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.delete(
      `/api/Character/${id}`,options
    );
  }

export const getDeleteApiCharacterIdUrl = (id: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Character/${id}`,
    baseURL: '',


  });
}




export const getDeleteApiCharacterIdMutationKey = () => ['deleteApiCharacterId'] as const;

export const getDeleteApiCharacterIdMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCharacterId>>, TError,DeleteApiCharacterIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCharacterId>>, TError,DeleteApiCharacterIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiCharacterIdMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCharacterId>>, DeleteApiCharacterIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteApiCharacterId(id,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiCharacterIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCharacterId>>>

    export type DeleteApiCharacterIdMutationError = AxiosError<unknown>
    export type DeleteApiCharacterIdMutationVariables = {id: string}

    /**
 * @summary Permanently deletes a character from the campaign.
 */
export const useDeleteApiCharacterId = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCharacterId>>, TError,DeleteApiCharacterIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiCharacterId>>,
        TError,
        DeleteApiCharacterIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiCharacterIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Creates a new character for a game session.
 */
export const postApiCharacter = (
    createCharacterDto?: CreateCharacterDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CharacterDto>> => {


    return axios.post(
      `/api/Character`,
      createCharacterDto,options
    );
  }

export const getPostApiCharacterUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Character`,
    baseURL: '',


  });
}




export const getPostApiCharacterMutationKey = () => ['postApiCharacter'] as const;

export const getPostApiCharacterMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCharacter>>, TError,PostApiCharacterMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiCharacter>>, TError,PostApiCharacterMutationVariables, TContext> => {

const mutationKey = getPostApiCharacterMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCharacter>>, PostApiCharacterMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiCharacter(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCharacterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCharacter>>>
    export type PostApiCharacterMutationBody = CreateCharacterDto | undefined
    export type PostApiCharacterMutationError = AxiosError<unknown>
    export type PostApiCharacterMutationVariables = {data?: CreateCharacterDto}

    /**
 * @summary Creates a new character for a game session.
 */
export const usePostApiCharacter = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCharacter>>, TError,PostApiCharacterMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCharacter>>,
        TError,
        PostApiCharacterMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiCharacterMutationOptions(options), queryClient);
    }
