// <auto-generated />
using System;
using GameMapBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameMapBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921112222_InitialGameMapSetup")]
    partial class InitialGameMapSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("GameMapBackend.Features.Character.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassIndex")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridY")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlayerCharacter")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MapId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonsterIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceIndex")
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeInCells")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeedInFeet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GameMapBackend.Features.Compendium.DndClassEntity", b =>
                {
                    b.Property<string>("Index")
                        .HasColumnType("TEXT")
                        .HasColumnName("index");

                    b.Property<int>("HitDie")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hit_die");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Index");

                    b.ToTable("dnd_classes", (string)null);
                });

            modelBuilder.Entity("GameMapBackend.Features.Compendium.DndConditionEntity", b =>
                {
                    b.Property<string>("Index")
                        .HasColumnType("TEXT")
                        .HasColumnName("index");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT")
                        .HasColumnName("desc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Index");

                    b.ToTable("dnd_conditions", (string)null);
                });

            modelBuilder.Entity("GameMapBackend.Features.Compendium.DndMonsterEntity", b =>
                {
                    b.Property<string>("Index")
                        .HasColumnType("TEXT")
                        .HasColumnName("index");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER")
                        .HasColumnName("armor_class");

                    b.Property<double>("ChallengeRating")
                        .HasColumnType("REAL")
                        .HasColumnName("challenge_rating");

                    b.Property<int>("HitPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hit_points");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT")
                        .HasColumnName("size");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Index");

                    b.ToTable("dnd_monsters", (string)null);
                });

            modelBuilder.Entity("GameMapBackend.Features.Compendium.DndRaceEntity", b =>
                {
                    b.Property<string>("Index")
                        .HasColumnType("TEXT")
                        .HasColumnName("index");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("speed");

                    b.HasKey("Index");

                    b.ToTable("dnd_races", (string)null);
                });

            modelBuilder.Entity("GameMapBackend.Features.Compendium.DndSpellEntity", b =>
                {
                    b.Property<string>("Index")
                        .HasColumnType("TEXT")
                        .HasColumnName("index");

                    b.Property<bool>("Concentration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("concentration");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT")
                        .HasColumnName("desc");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT")
                        .HasColumnName("duration");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Range")
                        .HasColumnType("TEXT")
                        .HasColumnName("range");

                    b.HasKey("Index");

                    b.ToTable("dnd_spells", (string)null);
                });

            modelBuilder.Entity("GameMapBackend.Features.GameSession.GameSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveMapId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DungeonMasterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveMapId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("GameMapBackend.Features.GameSession.SessionParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedCharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDungeonMaster")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCharacterId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("SessionParticipants");
                });

            modelBuilder.Entity("GameMapBackend.Features.Grid.GridEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CellSizeInPixels")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Columns")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GridColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MapId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OffsetX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffsetY")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Opacity")
                        .HasColumnType("REAL");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MapId")
                        .IsUnique();

                    b.ToTable("Grids");
                });

            modelBuilder.Entity("GameMapBackend.Features.Map.MapEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("GameMapBackend.Features.Spell.ActiveSpellEffectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CastAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CasterCharacterId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationInRounds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EffectColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MapId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RadiusInCells")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresConcentration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shape")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpellIndex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpellName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetGridX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetGridY")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CasterCharacterId");

                    b.HasIndex("MapId");

                    b.ToTable("ActiveSpellEffects");
                });

            modelBuilder.Entity("GameMapBackend.Features.Character.CharacterEntity", b =>
                {
                    b.HasOne("GameMapBackend.Features.Map.MapEntity", "Map")
                        .WithMany("Characters")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("GameMapBackend.Features.GameSession.GameSessionEntity", b =>
                {
                    b.HasOne("GameMapBackend.Features.Map.MapEntity", "ActiveMap")
                        .WithMany()
                        .HasForeignKey("ActiveMapId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveMap");
                });

            modelBuilder.Entity("GameMapBackend.Features.GameSession.SessionParticipantEntity", b =>
                {
                    b.HasOne("GameMapBackend.Features.Character.CharacterEntity", "AssignedCharacter")
                        .WithMany()
                        .HasForeignKey("AssignedCharacterId");

                    b.HasOne("GameMapBackend.Features.GameSession.GameSessionEntity", "GameSession")
                        .WithMany("Participants")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedCharacter");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("GameMapBackend.Features.Grid.GridEntity", b =>
                {
                    b.HasOne("GameMapBackend.Features.Map.MapEntity", "Map")
                        .WithOne("Grid")
                        .HasForeignKey("GameMapBackend.Features.Grid.GridEntity", "MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("GameMapBackend.Features.Spell.ActiveSpellEffectEntity", b =>
                {
                    b.HasOne("GameMapBackend.Features.Character.CharacterEntity", "CasterCharacter")
                        .WithMany()
                        .HasForeignKey("CasterCharacterId");

                    b.HasOne("GameMapBackend.Features.Map.MapEntity", "Map")
                        .WithMany("ActiveSpells")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CasterCharacter");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("GameMapBackend.Features.GameSession.GameSessionEntity", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("GameMapBackend.Features.Map.MapEntity", b =>
                {
                    b.Navigation("ActiveSpells");

                    b.Navigation("Characters");

                    b.Navigation("Grid");
                });
#pragma warning restore 612, 618
        }
    }
}
