/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */

export interface CreateCharacterDto {
  gameSessionId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  tokenImageUrl?: string | null;
  /** @nullable */
  ownerPlayerId?: string | null;
  /** @nullable */
  classIndex?: string | null;
  /** @nullable */
  raceIndex?: string | null;
  maxHp?: number;
  armorClass?: number;
  speedInFeet?: number;
}
