/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import type { ParticipantDto } from './participantDto';

export interface GameSessionDto {
  id?: string;
  /** @nullable */
  sessionName?: string | null;
  /** @nullable */
  joinCode?: string | null;
  /** @nullable */
  dungeonMasterId?: string | null;
  /** @nullable */
  activeMapId?: string | null;
  /** @nullable */
  participants?: ParticipantDto[] | null;
}
