/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */

export interface MapSummaryDto {
  id?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  widthInPixels?: number;
  heightInPixels?: number;
  createdAt?: string;
}
