/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */

export type PatchApiGameSessionIdActiveMapParams = {
/**
 * The unique identifier of the new active map.
 */
newMapId?: string;
};
