/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthRequestDto,
  AuthResponseDto
} from '../../model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export const postApiAuthRegister = (
    authRequestDto?: AuthRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponseDto>> => {


    return axios.post(
      `/api/Auth/register`,
      authRequestDto,options
    );
  }

export const getPostApiAuthRegisterUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Auth/register`,
    baseURL: '',


  });
}




export const getPostApiAuthRegisterMutationKey = () => ['postApiAuthRegister'] as const;

export const getPostApiAuthRegisterMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,PostApiAuthRegisterMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,PostApiAuthRegisterMutationVariables, TContext> => {

const mutationKey = getPostApiAuthRegisterMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRegister>>, PostApiAuthRegisterMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRegister(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRegister>>>
    export type PostApiAuthRegisterMutationBody = AuthRequestDto | undefined
    export type PostApiAuthRegisterMutationError = AxiosError<unknown>
    export type PostApiAuthRegisterMutationVariables = {data?: AuthRequestDto}

    export const usePostApiAuthRegister = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,PostApiAuthRegisterMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRegister>>,
        TError,
        PostApiAuthRegisterMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAuthRegisterMutationOptions(options), queryClient);
    }
    export const postApiAuthLogin = (
    authRequestDto?: AuthRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponseDto>> => {


    return axios.post(
      `/api/Auth/login`,
      authRequestDto,options
    );
  }

export const getPostApiAuthLoginUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Auth/login`,
    baseURL: '',


  });
}




export const getPostApiAuthLoginMutationKey = () => ['postApiAuthLogin'] as const;

export const getPostApiAuthLoginMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,PostApiAuthLoginMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,PostApiAuthLoginMutationVariables, TContext> => {

const mutationKey = getPostApiAuthLoginMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogin>>, PostApiAuthLoginMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthLogin(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogin>>>
    export type PostApiAuthLoginMutationBody = AuthRequestDto | undefined
    export type PostApiAuthLoginMutationError = AxiosError<unknown>
    export type PostApiAuthLoginMutationVariables = {data?: AuthRequestDto}

    export const usePostApiAuthLogin = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,PostApiAuthLoginMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        PostApiAuthLoginMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAuthLoginMutationOptions(options), queryClient);
    }
