/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ActiveSpellDto,
  CastSpellDto,
  DeleteApiSpellActiveIdParams,
  PostApiSpellMapMapIdCastParams,
  SpellCastEventDto
} from '../../model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Retrieves all active persistent spell templates on the specified battlemap.
 */
export const getApiSpellMapMapIdActive = (
    mapId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActiveSpellDto[]>> => {


    return axios.get(
      `/api/Spell/map/${mapId}/active`,options
    );
  }

export const getGetApiSpellMapMapIdActiveUrl = (mapId: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Spell/map/${mapId}/active`,
    baseURL: '',


  });
}




export const getGetApiSpellMapMapIdActiveQueryKey = (mapId: string,) => {
    return [
    `/api/Spell/map/${mapId}/active`
    ] as const;
    }


export const getGetApiSpellMapMapIdActiveQueryOptions = <TData = Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError = AxiosError<unknown>>(mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSpellMapMapIdActiveQueryKey(mapId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>> = ({ signal }) => getApiSpellMapMapIdActive(mapId, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: mapId !== null && mapId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSpellMapMapIdActiveQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>>
export type GetApiSpellMapMapIdActiveQueryError = AxiosError<unknown>


export function useGetApiSpellMapMapIdActive<TData = Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError = AxiosError<unknown>>(
 mapId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>,
          TError,
          Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSpellMapMapIdActive<TData = Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError = AxiosError<unknown>>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>,
          TError,
          Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSpellMapMapIdActive<TData = Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError = AxiosError<unknown>>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves all active persistent spell templates on the specified battlemap.
 */

export function useGetApiSpellMapMapIdActive<TData = Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError = AxiosError<unknown>>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSpellMapMapIdActiveQueryOptions(mapId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Casts a spell at target grid coordinates, calculating area of effect and concentration.
 */
export const postApiSpellMapMapIdCast = (
    mapId: string,
    castSpellDto?: CastSpellDto,
    params?: PostApiSpellMapMapIdCastParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SpellCastEventDto>> => {


    return axios.post(
      `/api/Spell/map/${mapId}/cast`,
      castSpellDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getPostApiSpellMapMapIdCastUrl = (mapId: string,
    params?: PostApiSpellMapMapIdCastParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Spell/map/${mapId}/cast`,
    baseURL: '',
    params,

  });
}




export const getPostApiSpellMapMapIdCastMutationKey = () => ['postApiSpellMapMapIdCast'] as const;

export const getPostApiSpellMapMapIdCastMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSpellMapMapIdCast>>, TError,PostApiSpellMapMapIdCastMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSpellMapMapIdCast>>, TError,PostApiSpellMapMapIdCastMutationVariables, TContext> => {

const mutationKey = getPostApiSpellMapMapIdCastMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSpellMapMapIdCast>>, PostApiSpellMapMapIdCastMutationVariables> = (props) => {
          const {mapId,data,params} = props ?? {};

          return  postApiSpellMapMapIdCast(mapId,data,params,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiSpellMapMapIdCastMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSpellMapMapIdCast>>>
    export type PostApiSpellMapMapIdCastMutationBody = CastSpellDto | undefined
    export type PostApiSpellMapMapIdCastMutationError = AxiosError<unknown>
    export type PostApiSpellMapMapIdCastMutationVariables = {mapId: string;data?: CastSpellDto;params?: PostApiSpellMapMapIdCastParams}

    /**
 * @summary Casts a spell at target grid coordinates, calculating area of effect and concentration.
 */
export const usePostApiSpellMapMapIdCast = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSpellMapMapIdCast>>, TError,PostApiSpellMapMapIdCastMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSpellMapMapIdCast>>,
        TError,
        PostApiSpellMapMapIdCastMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiSpellMapMapIdCastMutationOptions(options), queryClient);
    }
    /**
 * @summary Dismisses an active persistent spell effect from the map.
 */
export const deleteApiSpellActiveId = (
    id: string,
    params?: DeleteApiSpellActiveIdParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.delete(
      `/api/Spell/active/${id}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getDeleteApiSpellActiveIdUrl = (id: string,
    params?: DeleteApiSpellActiveIdParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Spell/active/${id}`,
    baseURL: '',
    params,

  });
}




export const getDeleteApiSpellActiveIdMutationKey = () => ['deleteApiSpellActiveId'] as const;

export const getDeleteApiSpellActiveIdMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiSpellActiveId>>, TError,DeleteApiSpellActiveIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiSpellActiveId>>, TError,DeleteApiSpellActiveIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiSpellActiveIdMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiSpellActiveId>>, DeleteApiSpellActiveIdMutationVariables> = (props) => {
          const {id,params} = props ?? {};

          return  deleteApiSpellActiveId(id,params,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiSpellActiveIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiSpellActiveId>>>

    export type DeleteApiSpellActiveIdMutationError = AxiosError<unknown>
    export type DeleteApiSpellActiveIdMutationVariables = {id: string;params?: DeleteApiSpellActiveIdParams}

    /**
 * @summary Dismisses an active persistent spell effect from the map.
 */
export const useDeleteApiSpellActiveId = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiSpellActiveId>>, TError,DeleteApiSpellActiveIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiSpellActiveId>>,
        TError,
        DeleteApiSpellActiveIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiSpellActiveIdMutationOptions(options), queryClient);
    }
