/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActiveSpellDto,
  CastSpellDto,
  DeleteApiSpellActiveIdParams,
  PostApiSpellMapMapIdCastParams,
  SpellCastEventDto
} from '../../model';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiSpellMapMapIdActiveResponse200TextPlain = {
  data: ActiveSpellDto[]
  status: 200
}

export type getApiSpellMapMapIdActiveResponse200ApplicationJson = {
  data: ActiveSpellDto[]
  status: 200
}

export type getApiSpellMapMapIdActiveResponse200TextJson = {
  data: ActiveSpellDto[]
  status: 200
}

export type getApiSpellMapMapIdActiveResponseSuccess = (getApiSpellMapMapIdActiveResponse200TextPlain | getApiSpellMapMapIdActiveResponse200ApplicationJson | getApiSpellMapMapIdActiveResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiSpellMapMapIdActiveResponse = (getApiSpellMapMapIdActiveResponseSuccess)

export const getGetApiSpellMapMapIdActiveUrl = (mapId: string,) => {




  return `/api/Spell/map/${mapId}/active`
}

/**
 * @summary Retrieves all active persistent spell templates on the specified battlemap.
 */
export const getApiSpellMapMapIdActive = async (mapId: string, options?: Parameters<typeof customInstance>[1]): Promise<getApiSpellMapMapIdActiveResponse> => {

  return customInstance<getApiSpellMapMapIdActiveResponse>(getGetApiSpellMapMapIdActiveUrl(mapId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiSpellMapMapIdActiveQueryKey = (mapId: string,) => {
    return [
    `/api/Spell/map/${mapId}/active`
    ] as const;
    }


export const getGetApiSpellMapMapIdActiveQueryOptions = <TData = Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError = unknown>(mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSpellMapMapIdActiveQueryKey(mapId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>> = ({ signal }) => getApiSpellMapMapIdActive(mapId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: mapId !== null && mapId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSpellMapMapIdActiveQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>>
export type GetApiSpellMapMapIdActiveQueryError = unknown


export function useGetApiSpellMapMapIdActive<TData = Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError = unknown>(
 mapId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>,
          TError,
          Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSpellMapMapIdActive<TData = Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError = unknown>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>,
          TError,
          Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSpellMapMapIdActive<TData = Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError = unknown>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves all active persistent spell templates on the specified battlemap.
 */

export function useGetApiSpellMapMapIdActive<TData = Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError = unknown>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSpellMapMapIdActive>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSpellMapMapIdActiveQueryOptions(mapId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiSpellMapMapIdCastResponse200TextPlain = {
  data: SpellCastEventDto
  status: 200
}

export type postApiSpellMapMapIdCastResponse200ApplicationJson = {
  data: SpellCastEventDto
  status: 200
}

export type postApiSpellMapMapIdCastResponse200TextJson = {
  data: SpellCastEventDto
  status: 200
}

export type postApiSpellMapMapIdCastResponseSuccess = (postApiSpellMapMapIdCastResponse200TextPlain | postApiSpellMapMapIdCastResponse200ApplicationJson | postApiSpellMapMapIdCastResponse200TextJson) & {
  headers: Headers;
};
;

export type postApiSpellMapMapIdCastResponse = (postApiSpellMapMapIdCastResponseSuccess)

export const getPostApiSpellMapMapIdCastUrl = (mapId: string,
    params?: PostApiSpellMapMapIdCastParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Spell/map/${mapId}/cast?${stringifiedParams}` : `/api/Spell/map/${mapId}/cast`
}

/**
 * @summary Casts a spell at target grid coordinates, calculating area of effect and concentration.
 */
export const postApiSpellMapMapIdCast = async (mapId: string,
    castSpellDto?: CastSpellDto,
    params?: PostApiSpellMapMapIdCastParams, options?: Parameters<typeof customInstance>[1]): Promise<postApiSpellMapMapIdCastResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<postApiSpellMapMapIdCastResponse>(getPostApiSpellMapMapIdCastUrl(mapId,params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(castSpellDto)
  }
);}





export const getPostApiSpellMapMapIdCastMutationKey = () => ['postApiSpellMapMapIdCast'] as const;

export const getPostApiSpellMapMapIdCastMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSpellMapMapIdCast>>, TError,PostApiSpellMapMapIdCastMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSpellMapMapIdCast>>, TError,PostApiSpellMapMapIdCastMutationVariables, TContext> => {

const mutationKey = getPostApiSpellMapMapIdCastMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSpellMapMapIdCast>>, PostApiSpellMapMapIdCastMutationVariables> = (props) => {
          const {mapId,data,params} = props ?? {};

          return  postApiSpellMapMapIdCast(mapId,data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiSpellMapMapIdCastMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSpellMapMapIdCast>>>
    export type PostApiSpellMapMapIdCastMutationBody = CastSpellDto | undefined
    export type PostApiSpellMapMapIdCastMutationError = unknown
    export type PostApiSpellMapMapIdCastMutationVariables = {mapId: string;data?: CastSpellDto;params?: PostApiSpellMapMapIdCastParams}

    /**
 * @summary Casts a spell at target grid coordinates, calculating area of effect and concentration.
 */
export const usePostApiSpellMapMapIdCast = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSpellMapMapIdCast>>, TError,PostApiSpellMapMapIdCastMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSpellMapMapIdCast>>,
        TError,
        PostApiSpellMapMapIdCastMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiSpellMapMapIdCastMutationOptions(options), queryClient);
    }
    export type deleteApiSpellActiveIdResponse200 = {
  data: void
  status: 200
}

export type deleteApiSpellActiveIdResponseSuccess = (deleteApiSpellActiveIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiSpellActiveIdResponse = (deleteApiSpellActiveIdResponseSuccess)

export const getDeleteApiSpellActiveIdUrl = (id: string,
    params?: DeleteApiSpellActiveIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Spell/active/${id}?${stringifiedParams}` : `/api/Spell/active/${id}`
}

/**
 * @summary Dismisses an active persistent spell effect from the map.
 */
export const deleteApiSpellActiveId = async (id: string,
    params?: DeleteApiSpellActiveIdParams, options?: Parameters<typeof customInstance>[1]): Promise<deleteApiSpellActiveIdResponse> => {

  return customInstance<deleteApiSpellActiveIdResponse>(getDeleteApiSpellActiveIdUrl(id,params),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiSpellActiveIdMutationKey = () => ['deleteApiSpellActiveId'] as const;

export const getDeleteApiSpellActiveIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiSpellActiveId>>, TError,DeleteApiSpellActiveIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiSpellActiveId>>, TError,DeleteApiSpellActiveIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiSpellActiveIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiSpellActiveId>>, DeleteApiSpellActiveIdMutationVariables> = (props) => {
          const {id,params} = props ?? {};

          return  deleteApiSpellActiveId(id,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiSpellActiveIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiSpellActiveId>>>

    export type DeleteApiSpellActiveIdMutationError = unknown
    export type DeleteApiSpellActiveIdMutationVariables = {id: string;params?: DeleteApiSpellActiveIdParams}

    /**
 * @summary Dismisses an active persistent spell effect from the map.
 */
export const useDeleteApiSpellActiveId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiSpellActiveId>>, TError,DeleteApiSpellActiveIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiSpellActiveId>>,
        TError,
        DeleteApiSpellActiveIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiSpellActiveIdMutationOptions(options), queryClient);
    }
