/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiTokenIdParams,
  GetApiTokenMapMapIdParams,
  MapTokenDto,
  MoveTokenDto,
  PatchApiTokenIdHpParams,
  PatchApiTokenIdMoveParams,
  PlaceCharacterTokenDto,
  PostApiTokenMapMapIdPlaceCharacterParams,
  PostApiTokenMapMapIdSpawnMonsterParams,
  SpawnMonsterTokenDto,
  UpdateTokenHpDto
} from '../../model';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiTokenMapMapIdResponse200TextPlain = {
  data: MapTokenDto[]
  status: 200
}

export type getApiTokenMapMapIdResponse200ApplicationJson = {
  data: MapTokenDto[]
  status: 200
}

export type getApiTokenMapMapIdResponse200TextJson = {
  data: MapTokenDto[]
  status: 200
}

export type getApiTokenMapMapIdResponseSuccess = (getApiTokenMapMapIdResponse200TextPlain | getApiTokenMapMapIdResponse200ApplicationJson | getApiTokenMapMapIdResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiTokenMapMapIdResponse = (getApiTokenMapMapIdResponseSuccess)

export const getGetApiTokenMapMapIdUrl = (mapId: string,
    params?: GetApiTokenMapMapIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Token/map/${mapId}?${stringifiedParams}` : `/api/Token/map/${mapId}`
}

/**
 * @summary Retrieves all active tokens currently placed on the specified battlemap.
 */
export const getApiTokenMapMapId = async (mapId: string,
    params?: GetApiTokenMapMapIdParams, options?: Parameters<typeof customInstance>[1]): Promise<getApiTokenMapMapIdResponse> => {

  return customInstance<getApiTokenMapMapIdResponse>(getGetApiTokenMapMapIdUrl(mapId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiTokenMapMapIdQueryKey = (mapId: string,
    params?: GetApiTokenMapMapIdParams,) => {
    return [
    `/api/Token/map/${mapId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiTokenMapMapIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError = unknown>(mapId: string,
    params?: GetApiTokenMapMapIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTokenMapMapIdQueryKey(mapId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTokenMapMapId>>> = ({ signal }) => getApiTokenMapMapId(mapId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: mapId !== null && mapId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTokenMapMapIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTokenMapMapId>>>
export type GetApiTokenMapMapIdQueryError = unknown


export function useGetApiTokenMapMapId<TData = Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError = unknown>(
 mapId: string,
    params: undefined |  GetApiTokenMapMapIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTokenMapMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiTokenMapMapId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTokenMapMapId<TData = Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError = unknown>(
 mapId: string,
    params?: GetApiTokenMapMapIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTokenMapMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiTokenMapMapId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTokenMapMapId<TData = Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError = unknown>(
 mapId: string,
    params?: GetApiTokenMapMapIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves all active tokens currently placed on the specified battlemap.
 */

export function useGetApiTokenMapMapId<TData = Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError = unknown>(
 mapId: string,
    params?: GetApiTokenMapMapIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTokenMapMapIdQueryOptions(mapId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiTokenMapMapIdPlaceCharacterResponse200TextPlain = {
  data: MapTokenDto
  status: 200
}

export type postApiTokenMapMapIdPlaceCharacterResponse200ApplicationJson = {
  data: MapTokenDto
  status: 200
}

export type postApiTokenMapMapIdPlaceCharacterResponse200TextJson = {
  data: MapTokenDto
  status: 200
}

export type postApiTokenMapMapIdPlaceCharacterResponseSuccess = (postApiTokenMapMapIdPlaceCharacterResponse200TextPlain | postApiTokenMapMapIdPlaceCharacterResponse200ApplicationJson | postApiTokenMapMapIdPlaceCharacterResponse200TextJson) & {
  headers: Headers;
};
;

export type postApiTokenMapMapIdPlaceCharacterResponse = (postApiTokenMapMapIdPlaceCharacterResponseSuccess)

export const getPostApiTokenMapMapIdPlaceCharacterUrl = (mapId: string,
    params?: PostApiTokenMapMapIdPlaceCharacterParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Token/map/${mapId}/place-character?${stringifiedParams}` : `/api/Token/map/${mapId}/place-character`
}

/**
 * @summary Places a player character token onto the battlemap at the specified grid position.
 */
export const postApiTokenMapMapIdPlaceCharacter = async (mapId: string,
    placeCharacterTokenDto?: PlaceCharacterTokenDto,
    params?: PostApiTokenMapMapIdPlaceCharacterParams, options?: Parameters<typeof customInstance>[1]): Promise<postApiTokenMapMapIdPlaceCharacterResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<postApiTokenMapMapIdPlaceCharacterResponse>(getPostApiTokenMapMapIdPlaceCharacterUrl(mapId,params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(placeCharacterTokenDto)
  }
);}





export const getPostApiTokenMapMapIdPlaceCharacterMutationKey = () => ['postApiTokenMapMapIdPlaceCharacter'] as const;

export const getPostApiTokenMapMapIdPlaceCharacterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTokenMapMapIdPlaceCharacter>>, TError,PostApiTokenMapMapIdPlaceCharacterMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiTokenMapMapIdPlaceCharacter>>, TError,PostApiTokenMapMapIdPlaceCharacterMutationVariables, TContext> => {

const mutationKey = getPostApiTokenMapMapIdPlaceCharacterMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiTokenMapMapIdPlaceCharacter>>, PostApiTokenMapMapIdPlaceCharacterMutationVariables> = (props) => {
          const {mapId,data,params} = props ?? {};

          return  postApiTokenMapMapIdPlaceCharacter(mapId,data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiTokenMapMapIdPlaceCharacterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiTokenMapMapIdPlaceCharacter>>>
    export type PostApiTokenMapMapIdPlaceCharacterMutationBody = PlaceCharacterTokenDto | undefined
    export type PostApiTokenMapMapIdPlaceCharacterMutationError = unknown
    export type PostApiTokenMapMapIdPlaceCharacterMutationVariables = {mapId: string;data?: PlaceCharacterTokenDto;params?: PostApiTokenMapMapIdPlaceCharacterParams}

    /**
 * @summary Places a player character token onto the battlemap at the specified grid position.
 */
export const usePostApiTokenMapMapIdPlaceCharacter = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTokenMapMapIdPlaceCharacter>>, TError,PostApiTokenMapMapIdPlaceCharacterMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiTokenMapMapIdPlaceCharacter>>,
        TError,
        PostApiTokenMapMapIdPlaceCharacterMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiTokenMapMapIdPlaceCharacterMutationOptions(options), queryClient);
    }
    export type postApiTokenMapMapIdSpawnMonsterResponse200TextPlain = {
  data: MapTokenDto
  status: 200
}

export type postApiTokenMapMapIdSpawnMonsterResponse200ApplicationJson = {
  data: MapTokenDto
  status: 200
}

export type postApiTokenMapMapIdSpawnMonsterResponse200TextJson = {
  data: MapTokenDto
  status: 200
}

export type postApiTokenMapMapIdSpawnMonsterResponseSuccess = (postApiTokenMapMapIdSpawnMonsterResponse200TextPlain | postApiTokenMapMapIdSpawnMonsterResponse200ApplicationJson | postApiTokenMapMapIdSpawnMonsterResponse200TextJson) & {
  headers: Headers;
};
;

export type postApiTokenMapMapIdSpawnMonsterResponse = (postApiTokenMapMapIdSpawnMonsterResponseSuccess)

export const getPostApiTokenMapMapIdSpawnMonsterUrl = (mapId: string,
    params?: PostApiTokenMapMapIdSpawnMonsterParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Token/map/${mapId}/spawn-monster?${stringifiedParams}` : `/api/Token/map/${mapId}/spawn-monster`
}

/**
 * @summary Spawns a monster token onto the battlemap from the D&D SRD compendium.
 */
export const postApiTokenMapMapIdSpawnMonster = async (mapId: string,
    spawnMonsterTokenDto?: SpawnMonsterTokenDto,
    params?: PostApiTokenMapMapIdSpawnMonsterParams, options?: Parameters<typeof customInstance>[1]): Promise<postApiTokenMapMapIdSpawnMonsterResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<postApiTokenMapMapIdSpawnMonsterResponse>(getPostApiTokenMapMapIdSpawnMonsterUrl(mapId,params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(spawnMonsterTokenDto)
  }
);}





export const getPostApiTokenMapMapIdSpawnMonsterMutationKey = () => ['postApiTokenMapMapIdSpawnMonster'] as const;

export const getPostApiTokenMapMapIdSpawnMonsterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTokenMapMapIdSpawnMonster>>, TError,PostApiTokenMapMapIdSpawnMonsterMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiTokenMapMapIdSpawnMonster>>, TError,PostApiTokenMapMapIdSpawnMonsterMutationVariables, TContext> => {

const mutationKey = getPostApiTokenMapMapIdSpawnMonsterMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiTokenMapMapIdSpawnMonster>>, PostApiTokenMapMapIdSpawnMonsterMutationVariables> = (props) => {
          const {mapId,data,params} = props ?? {};

          return  postApiTokenMapMapIdSpawnMonster(mapId,data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiTokenMapMapIdSpawnMonsterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiTokenMapMapIdSpawnMonster>>>
    export type PostApiTokenMapMapIdSpawnMonsterMutationBody = SpawnMonsterTokenDto | undefined
    export type PostApiTokenMapMapIdSpawnMonsterMutationError = unknown
    export type PostApiTokenMapMapIdSpawnMonsterMutationVariables = {mapId: string;data?: SpawnMonsterTokenDto;params?: PostApiTokenMapMapIdSpawnMonsterParams}

    /**
 * @summary Spawns a monster token onto the battlemap from the D&D SRD compendium.
 */
export const usePostApiTokenMapMapIdSpawnMonster = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTokenMapMapIdSpawnMonster>>, TError,PostApiTokenMapMapIdSpawnMonsterMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiTokenMapMapIdSpawnMonster>>,
        TError,
        PostApiTokenMapMapIdSpawnMonsterMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiTokenMapMapIdSpawnMonsterMutationOptions(options), queryClient);
    }
    export type patchApiTokenIdMoveResponse200TextPlain = {
  data: MapTokenDto
  status: 200
}

export type patchApiTokenIdMoveResponse200ApplicationJson = {
  data: MapTokenDto
  status: 200
}

export type patchApiTokenIdMoveResponse200TextJson = {
  data: MapTokenDto
  status: 200
}

export type patchApiTokenIdMoveResponseSuccess = (patchApiTokenIdMoveResponse200TextPlain | patchApiTokenIdMoveResponse200ApplicationJson | patchApiTokenIdMoveResponse200TextJson) & {
  headers: Headers;
};
;

export type patchApiTokenIdMoveResponse = (patchApiTokenIdMoveResponseSuccess)

export const getPatchApiTokenIdMoveUrl = (id: string,
    params?: PatchApiTokenIdMoveParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Token/${id}/move?${stringifiedParams}` : `/api/Token/${id}/move`
}

/**
 * @summary Moves an existing token to a new grid position.
 */
export const patchApiTokenIdMove = async (id: string,
    moveTokenDto?: MoveTokenDto,
    params?: PatchApiTokenIdMoveParams, options?: Parameters<typeof customInstance>[1]): Promise<patchApiTokenIdMoveResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<patchApiTokenIdMoveResponse>(getPatchApiTokenIdMoveUrl(id,params),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(moveTokenDto)
  }
);}





export const getPatchApiTokenIdMoveMutationKey = () => ['patchApiTokenIdMove'] as const;

export const getPatchApiTokenIdMoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTokenIdMove>>, TError,PatchApiTokenIdMoveMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiTokenIdMove>>, TError,PatchApiTokenIdMoveMutationVariables, TContext> => {

const mutationKey = getPatchApiTokenIdMoveMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiTokenIdMove>>, PatchApiTokenIdMoveMutationVariables> = (props) => {
          const {id,data,params} = props ?? {};

          return  patchApiTokenIdMove(id,data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiTokenIdMoveMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiTokenIdMove>>>
    export type PatchApiTokenIdMoveMutationBody = MoveTokenDto | undefined
    export type PatchApiTokenIdMoveMutationError = unknown
    export type PatchApiTokenIdMoveMutationVariables = {id: string;data?: MoveTokenDto;params?: PatchApiTokenIdMoveParams}

    /**
 * @summary Moves an existing token to a new grid position.
 */
export const usePatchApiTokenIdMove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTokenIdMove>>, TError,PatchApiTokenIdMoveMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiTokenIdMove>>,
        TError,
        PatchApiTokenIdMoveMutationVariables,
        TContext
      > => {
      return useMutation(getPatchApiTokenIdMoveMutationOptions(options), queryClient);
    }
    export type patchApiTokenIdHpResponse200TextPlain = {
  data: MapTokenDto
  status: 200
}

export type patchApiTokenIdHpResponse200ApplicationJson = {
  data: MapTokenDto
  status: 200
}

export type patchApiTokenIdHpResponse200TextJson = {
  data: MapTokenDto
  status: 200
}

export type patchApiTokenIdHpResponseSuccess = (patchApiTokenIdHpResponse200TextPlain | patchApiTokenIdHpResponse200ApplicationJson | patchApiTokenIdHpResponse200TextJson) & {
  headers: Headers;
};
;

export type patchApiTokenIdHpResponse = (patchApiTokenIdHpResponseSuccess)

export const getPatchApiTokenIdHpUrl = (id: string,
    params?: PatchApiTokenIdHpParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Token/${id}/hp?${stringifiedParams}` : `/api/Token/${id}/hp`
}

/**
 * @summary Updates the current Hit Points (HP) of a token on the board.
 */
export const patchApiTokenIdHp = async (id: string,
    updateTokenHpDto?: UpdateTokenHpDto,
    params?: PatchApiTokenIdHpParams, options?: Parameters<typeof customInstance>[1]): Promise<patchApiTokenIdHpResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<patchApiTokenIdHpResponse>(getPatchApiTokenIdHpUrl(id,params),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateTokenHpDto)
  }
);}





export const getPatchApiTokenIdHpMutationKey = () => ['patchApiTokenIdHp'] as const;

export const getPatchApiTokenIdHpMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTokenIdHp>>, TError,PatchApiTokenIdHpMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiTokenIdHp>>, TError,PatchApiTokenIdHpMutationVariables, TContext> => {

const mutationKey = getPatchApiTokenIdHpMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiTokenIdHp>>, PatchApiTokenIdHpMutationVariables> = (props) => {
          const {id,data,params} = props ?? {};

          return  patchApiTokenIdHp(id,data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiTokenIdHpMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiTokenIdHp>>>
    export type PatchApiTokenIdHpMutationBody = UpdateTokenHpDto | undefined
    export type PatchApiTokenIdHpMutationError = unknown
    export type PatchApiTokenIdHpMutationVariables = {id: string;data?: UpdateTokenHpDto;params?: PatchApiTokenIdHpParams}

    /**
 * @summary Updates the current Hit Points (HP) of a token on the board.
 */
export const usePatchApiTokenIdHp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTokenIdHp>>, TError,PatchApiTokenIdHpMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiTokenIdHp>>,
        TError,
        PatchApiTokenIdHpMutationVariables,
        TContext
      > => {
      return useMutation(getPatchApiTokenIdHpMutationOptions(options), queryClient);
    }
    export type deleteApiTokenIdResponse200 = {
  data: void
  status: 200
}

export type deleteApiTokenIdResponseSuccess = (deleteApiTokenIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiTokenIdResponse = (deleteApiTokenIdResponseSuccess)

export const getDeleteApiTokenIdUrl = (id: string,
    params?: DeleteApiTokenIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Token/${id}?${stringifiedParams}` : `/api/Token/${id}`
}

/**
 * @summary Removes a token permanently from the battlemap.
 */
export const deleteApiTokenId = async (id: string,
    params?: DeleteApiTokenIdParams, options?: Parameters<typeof customInstance>[1]): Promise<deleteApiTokenIdResponse> => {

  return customInstance<deleteApiTokenIdResponse>(getDeleteApiTokenIdUrl(id,params),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiTokenIdMutationKey = () => ['deleteApiTokenId'] as const;

export const getDeleteApiTokenIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiTokenId>>, TError,DeleteApiTokenIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiTokenId>>, TError,DeleteApiTokenIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiTokenIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiTokenId>>, DeleteApiTokenIdMutationVariables> = (props) => {
          const {id,params} = props ?? {};

          return  deleteApiTokenId(id,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiTokenIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiTokenId>>>

    export type DeleteApiTokenIdMutationError = unknown
    export type DeleteApiTokenIdMutationVariables = {id: string;params?: DeleteApiTokenIdParams}

    /**
 * @summary Removes a token permanently from the battlemap.
 */
export const useDeleteApiTokenId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiTokenId>>, TError,DeleteApiTokenIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiTokenId>>,
        TError,
        DeleteApiTokenIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiTokenIdMutationOptions(options), queryClient);
    }
