/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeleteApiTokenIdParams,
  GetApiTokenMapMapIdParams,
  MapTokenDto,
  MoveTokenDto,
  PatchApiTokenIdHpParams,
  PatchApiTokenIdMoveParams,
  PlaceCharacterTokenDto,
  PostApiTokenMapMapIdPlaceCharacterParams,
  PostApiTokenMapMapIdSpawnMonsterParams,
  SpawnMonsterTokenDto,
  UpdateTokenHpDto
} from '../../model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Retrieves all active tokens currently placed on the specified battlemap.
 */
export const getApiTokenMapMapId = (
    mapId: string,
    params?: GetApiTokenMapMapIdParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MapTokenDto[]>> => {


    return axios.get(
      `/api/Token/map/${mapId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getGetApiTokenMapMapIdUrl = (mapId: string,
    params?: GetApiTokenMapMapIdParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Token/map/${mapId}`,
    baseURL: '',
    params,

  });
}




export const getGetApiTokenMapMapIdQueryKey = (mapId: string,
    params?: GetApiTokenMapMapIdParams,) => {
    return [
    `/api/Token/map/${mapId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiTokenMapMapIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError = AxiosError<unknown>>(mapId: string,
    params?: GetApiTokenMapMapIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTokenMapMapIdQueryKey(mapId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTokenMapMapId>>> = ({ signal }) => getApiTokenMapMapId(mapId,params, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: mapId !== null && mapId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTokenMapMapIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTokenMapMapId>>>
export type GetApiTokenMapMapIdQueryError = AxiosError<unknown>


export function useGetApiTokenMapMapId<TData = Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError = AxiosError<unknown>>(
 mapId: string,
    params: undefined |  GetApiTokenMapMapIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTokenMapMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiTokenMapMapId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTokenMapMapId<TData = Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError = AxiosError<unknown>>(
 mapId: string,
    params?: GetApiTokenMapMapIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTokenMapMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiTokenMapMapId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTokenMapMapId<TData = Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError = AxiosError<unknown>>(
 mapId: string,
    params?: GetApiTokenMapMapIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves all active tokens currently placed on the specified battlemap.
 */

export function useGetApiTokenMapMapId<TData = Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError = AxiosError<unknown>>(
 mapId: string,
    params?: GetApiTokenMapMapIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTokenMapMapId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTokenMapMapIdQueryOptions(mapId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Places a player character token onto the battlemap at the specified grid position.
 */
export const postApiTokenMapMapIdPlaceCharacter = (
    mapId: string,
    placeCharacterTokenDto?: PlaceCharacterTokenDto,
    params?: PostApiTokenMapMapIdPlaceCharacterParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MapTokenDto>> => {


    return axios.post(
      `/api/Token/map/${mapId}/place-character`,
      placeCharacterTokenDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getPostApiTokenMapMapIdPlaceCharacterUrl = (mapId: string,
    params?: PostApiTokenMapMapIdPlaceCharacterParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Token/map/${mapId}/place-character`,
    baseURL: '',
    params,

  });
}




export const getPostApiTokenMapMapIdPlaceCharacterMutationKey = () => ['postApiTokenMapMapIdPlaceCharacter'] as const;

export const getPostApiTokenMapMapIdPlaceCharacterMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTokenMapMapIdPlaceCharacter>>, TError,PostApiTokenMapMapIdPlaceCharacterMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiTokenMapMapIdPlaceCharacter>>, TError,PostApiTokenMapMapIdPlaceCharacterMutationVariables, TContext> => {

const mutationKey = getPostApiTokenMapMapIdPlaceCharacterMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiTokenMapMapIdPlaceCharacter>>, PostApiTokenMapMapIdPlaceCharacterMutationVariables> = (props) => {
          const {mapId,data,params} = props ?? {};

          return  postApiTokenMapMapIdPlaceCharacter(mapId,data,params,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiTokenMapMapIdPlaceCharacterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiTokenMapMapIdPlaceCharacter>>>
    export type PostApiTokenMapMapIdPlaceCharacterMutationBody = PlaceCharacterTokenDto | undefined
    export type PostApiTokenMapMapIdPlaceCharacterMutationError = AxiosError<unknown>
    export type PostApiTokenMapMapIdPlaceCharacterMutationVariables = {mapId: string;data?: PlaceCharacterTokenDto;params?: PostApiTokenMapMapIdPlaceCharacterParams}

    /**
 * @summary Places a player character token onto the battlemap at the specified grid position.
 */
export const usePostApiTokenMapMapIdPlaceCharacter = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTokenMapMapIdPlaceCharacter>>, TError,PostApiTokenMapMapIdPlaceCharacterMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiTokenMapMapIdPlaceCharacter>>,
        TError,
        PostApiTokenMapMapIdPlaceCharacterMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiTokenMapMapIdPlaceCharacterMutationOptions(options), queryClient);
    }
    /**
 * @summary Spawns a monster token onto the battlemap from the D&D SRD compendium.
 */
export const postApiTokenMapMapIdSpawnMonster = (
    mapId: string,
    spawnMonsterTokenDto?: SpawnMonsterTokenDto,
    params?: PostApiTokenMapMapIdSpawnMonsterParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MapTokenDto>> => {


    return axios.post(
      `/api/Token/map/${mapId}/spawn-monster`,
      spawnMonsterTokenDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getPostApiTokenMapMapIdSpawnMonsterUrl = (mapId: string,
    params?: PostApiTokenMapMapIdSpawnMonsterParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Token/map/${mapId}/spawn-monster`,
    baseURL: '',
    params,

  });
}




export const getPostApiTokenMapMapIdSpawnMonsterMutationKey = () => ['postApiTokenMapMapIdSpawnMonster'] as const;

export const getPostApiTokenMapMapIdSpawnMonsterMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTokenMapMapIdSpawnMonster>>, TError,PostApiTokenMapMapIdSpawnMonsterMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiTokenMapMapIdSpawnMonster>>, TError,PostApiTokenMapMapIdSpawnMonsterMutationVariables, TContext> => {

const mutationKey = getPostApiTokenMapMapIdSpawnMonsterMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiTokenMapMapIdSpawnMonster>>, PostApiTokenMapMapIdSpawnMonsterMutationVariables> = (props) => {
          const {mapId,data,params} = props ?? {};

          return  postApiTokenMapMapIdSpawnMonster(mapId,data,params,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiTokenMapMapIdSpawnMonsterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiTokenMapMapIdSpawnMonster>>>
    export type PostApiTokenMapMapIdSpawnMonsterMutationBody = SpawnMonsterTokenDto | undefined
    export type PostApiTokenMapMapIdSpawnMonsterMutationError = AxiosError<unknown>
    export type PostApiTokenMapMapIdSpawnMonsterMutationVariables = {mapId: string;data?: SpawnMonsterTokenDto;params?: PostApiTokenMapMapIdSpawnMonsterParams}

    /**
 * @summary Spawns a monster token onto the battlemap from the D&D SRD compendium.
 */
export const usePostApiTokenMapMapIdSpawnMonster = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTokenMapMapIdSpawnMonster>>, TError,PostApiTokenMapMapIdSpawnMonsterMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiTokenMapMapIdSpawnMonster>>,
        TError,
        PostApiTokenMapMapIdSpawnMonsterMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiTokenMapMapIdSpawnMonsterMutationOptions(options), queryClient);
    }
    /**
 * @summary Moves an existing token to a new grid position.
 */
export const patchApiTokenIdMove = (
    id: string,
    moveTokenDto?: MoveTokenDto,
    params?: PatchApiTokenIdMoveParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MapTokenDto>> => {


    return axios.patch(
      `/api/Token/${id}/move`,
      moveTokenDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getPatchApiTokenIdMoveUrl = (id: string,
    params?: PatchApiTokenIdMoveParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Token/${id}/move`,
    baseURL: '',
    params,

  });
}




export const getPatchApiTokenIdMoveMutationKey = () => ['patchApiTokenIdMove'] as const;

export const getPatchApiTokenIdMoveMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTokenIdMove>>, TError,PatchApiTokenIdMoveMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiTokenIdMove>>, TError,PatchApiTokenIdMoveMutationVariables, TContext> => {

const mutationKey = getPatchApiTokenIdMoveMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiTokenIdMove>>, PatchApiTokenIdMoveMutationVariables> = (props) => {
          const {id,data,params} = props ?? {};

          return  patchApiTokenIdMove(id,data,params,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiTokenIdMoveMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiTokenIdMove>>>
    export type PatchApiTokenIdMoveMutationBody = MoveTokenDto | undefined
    export type PatchApiTokenIdMoveMutationError = AxiosError<unknown>
    export type PatchApiTokenIdMoveMutationVariables = {id: string;data?: MoveTokenDto;params?: PatchApiTokenIdMoveParams}

    /**
 * @summary Moves an existing token to a new grid position.
 */
export const usePatchApiTokenIdMove = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTokenIdMove>>, TError,PatchApiTokenIdMoveMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiTokenIdMove>>,
        TError,
        PatchApiTokenIdMoveMutationVariables,
        TContext
      > => {
      return useMutation(getPatchApiTokenIdMoveMutationOptions(options), queryClient);
    }
    /**
 * @summary Updates the current Hit Points (HP) of a token on the board.
 */
export const patchApiTokenIdHp = (
    id: string,
    updateTokenHpDto?: UpdateTokenHpDto,
    params?: PatchApiTokenIdHpParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MapTokenDto>> => {


    return axios.patch(
      `/api/Token/${id}/hp`,
      updateTokenHpDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getPatchApiTokenIdHpUrl = (id: string,
    params?: PatchApiTokenIdHpParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Token/${id}/hp`,
    baseURL: '',
    params,

  });
}




export const getPatchApiTokenIdHpMutationKey = () => ['patchApiTokenIdHp'] as const;

export const getPatchApiTokenIdHpMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTokenIdHp>>, TError,PatchApiTokenIdHpMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiTokenIdHp>>, TError,PatchApiTokenIdHpMutationVariables, TContext> => {

const mutationKey = getPatchApiTokenIdHpMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiTokenIdHp>>, PatchApiTokenIdHpMutationVariables> = (props) => {
          const {id,data,params} = props ?? {};

          return  patchApiTokenIdHp(id,data,params,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiTokenIdHpMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiTokenIdHp>>>
    export type PatchApiTokenIdHpMutationBody = UpdateTokenHpDto | undefined
    export type PatchApiTokenIdHpMutationError = AxiosError<unknown>
    export type PatchApiTokenIdHpMutationVariables = {id: string;data?: UpdateTokenHpDto;params?: PatchApiTokenIdHpParams}

    /**
 * @summary Updates the current Hit Points (HP) of a token on the board.
 */
export const usePatchApiTokenIdHp = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTokenIdHp>>, TError,PatchApiTokenIdHpMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiTokenIdHp>>,
        TError,
        PatchApiTokenIdHpMutationVariables,
        TContext
      > => {
      return useMutation(getPatchApiTokenIdHpMutationOptions(options), queryClient);
    }
    /**
 * @summary Removes a token permanently from the battlemap.
 */
export const deleteApiTokenId = (
    id: string,
    params?: DeleteApiTokenIdParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.delete(
      `/api/Token/${id}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getDeleteApiTokenIdUrl = (id: string,
    params?: DeleteApiTokenIdParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Token/${id}`,
    baseURL: '',
    params,

  });
}




export const getDeleteApiTokenIdMutationKey = () => ['deleteApiTokenId'] as const;

export const getDeleteApiTokenIdMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiTokenId>>, TError,DeleteApiTokenIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiTokenId>>, TError,DeleteApiTokenIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiTokenIdMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiTokenId>>, DeleteApiTokenIdMutationVariables> = (props) => {
          const {id,params} = props ?? {};

          return  deleteApiTokenId(id,params,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiTokenIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiTokenId>>>

    export type DeleteApiTokenIdMutationError = AxiosError<unknown>
    export type DeleteApiTokenIdMutationVariables = {id: string;params?: DeleteApiTokenIdParams}

    /**
 * @summary Removes a token permanently from the battlemap.
 */
export const useDeleteApiTokenId = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiTokenId>>, TError,DeleteApiTokenIdMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiTokenId>>,
        TError,
        DeleteApiTokenIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiTokenIdMutationOptions(options), queryClient);
    }
