/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CompendiumClassDto,
  CompendiumConditionDto,
  CompendiumMonsterDto,
  CompendiumRaceDto,
  CompendiumSpellDto,
  GetApiCompendiumMonstersParams,
  GetApiCompendiumSpellsParams
} from '../../model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Retrieves all available D&D classes for character creation.
 */
export const getApiCompendiumClasses = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CompendiumClassDto[]>> => {


    return axios.get(
      `/api/Compendium/classes`,options
    );
  }

export const getGetApiCompendiumClassesUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Compendium/classes`,
    baseURL: '',


  });
}




export const getGetApiCompendiumClassesQueryKey = () => {
    return [
    `/api/Compendium/classes`
    ] as const;
    }


export const getGetApiCompendiumClassesQueryOptions = <TData = Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCompendiumClassesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCompendiumClasses>>> = ({ signal }) => getApiCompendiumClasses({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCompendiumClassesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCompendiumClasses>>>
export type GetApiCompendiumClassesQueryError = AxiosError<unknown>


export function useGetApiCompendiumClasses<TData = Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumClasses>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumClasses>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumClasses<TData = Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumClasses>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumClasses>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumClasses<TData = Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves all available D&D classes for character creation.
 */

export function useGetApiCompendiumClasses<TData = Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCompendiumClassesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Retrieves all available D&D races for character creation.
 */
export const getApiCompendiumRaces = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CompendiumRaceDto[]>> => {


    return axios.get(
      `/api/Compendium/races`,options
    );
  }

export const getGetApiCompendiumRacesUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Compendium/races`,
    baseURL: '',


  });
}




export const getGetApiCompendiumRacesQueryKey = () => {
    return [
    `/api/Compendium/races`
    ] as const;
    }


export const getGetApiCompendiumRacesQueryOptions = <TData = Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCompendiumRacesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCompendiumRaces>>> = ({ signal }) => getApiCompendiumRaces({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCompendiumRacesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCompendiumRaces>>>
export type GetApiCompendiumRacesQueryError = AxiosError<unknown>


export function useGetApiCompendiumRaces<TData = Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumRaces>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumRaces>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumRaces<TData = Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumRaces>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumRaces>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumRaces<TData = Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves all available D&D races for character creation.
 */

export function useGetApiCompendiumRaces<TData = Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCompendiumRacesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Searches spells by name filter and optional spell level.
 */
export const getApiCompendiumSpells = (
    params?: GetApiCompendiumSpellsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CompendiumSpellDto[]>> => {


    return axios.get(
      `/api/Compendium/spells`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getGetApiCompendiumSpellsUrl = (params?: GetApiCompendiumSpellsParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Compendium/spells`,
    baseURL: '',
    params,

  });
}




export const getGetApiCompendiumSpellsQueryKey = (params?: GetApiCompendiumSpellsParams,) => {
    return [
    `/api/Compendium/spells`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiCompendiumSpellsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError = AxiosError<unknown>>(params?: GetApiCompendiumSpellsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCompendiumSpellsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCompendiumSpells>>> = ({ signal }) => getApiCompendiumSpells(params, { signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCompendiumSpellsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCompendiumSpells>>>
export type GetApiCompendiumSpellsQueryError = AxiosError<unknown>


export function useGetApiCompendiumSpells<TData = Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError = AxiosError<unknown>>(
 params: undefined |  GetApiCompendiumSpellsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumSpells>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumSpells>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumSpells<TData = Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError = AxiosError<unknown>>(
 params?: GetApiCompendiumSpellsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumSpells>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumSpells>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumSpells<TData = Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError = AxiosError<unknown>>(
 params?: GetApiCompendiumSpellsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Searches spells by name filter and optional spell level.
 */

export function useGetApiCompendiumSpells<TData = Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError = AxiosError<unknown>>(
 params?: GetApiCompendiumSpellsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCompendiumSpellsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Searches monsters by name filter.
 */
export const getApiCompendiumMonsters = (
    params?: GetApiCompendiumMonstersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CompendiumMonsterDto[]>> => {


    return axios.get(
      `/api/Compendium/monsters`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getGetApiCompendiumMonstersUrl = (params?: GetApiCompendiumMonstersParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Compendium/monsters`,
    baseURL: '',
    params,

  });
}




export const getGetApiCompendiumMonstersQueryKey = (params?: GetApiCompendiumMonstersParams,) => {
    return [
    `/api/Compendium/monsters`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiCompendiumMonstersQueryOptions = <TData = Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError = AxiosError<unknown>>(params?: GetApiCompendiumMonstersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCompendiumMonstersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCompendiumMonsters>>> = ({ signal }) => getApiCompendiumMonsters(params, { signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCompendiumMonstersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCompendiumMonsters>>>
export type GetApiCompendiumMonstersQueryError = AxiosError<unknown>


export function useGetApiCompendiumMonsters<TData = Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError = AxiosError<unknown>>(
 params: undefined |  GetApiCompendiumMonstersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumMonsters>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumMonsters>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumMonsters<TData = Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError = AxiosError<unknown>>(
 params?: GetApiCompendiumMonstersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumMonsters>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumMonsters>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumMonsters<TData = Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError = AxiosError<unknown>>(
 params?: GetApiCompendiumMonstersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Searches monsters by name filter.
 */

export function useGetApiCompendiumMonsters<TData = Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError = AxiosError<unknown>>(
 params?: GetApiCompendiumMonstersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCompendiumMonstersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Retrieves all standard D&D conditions.
 */
export const getApiCompendiumConditions = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CompendiumConditionDto[]>> => {


    return axios.get(
      `/api/Compendium/conditions`,options
    );
  }

export const getGetApiCompendiumConditionsUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/Compendium/conditions`,
    baseURL: '',


  });
}




export const getGetApiCompendiumConditionsQueryKey = () => {
    return [
    `/api/Compendium/conditions`
    ] as const;
    }


export const getGetApiCompendiumConditionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCompendiumConditionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCompendiumConditions>>> = ({ signal }) => getApiCompendiumConditions({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCompendiumConditionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCompendiumConditions>>>
export type GetApiCompendiumConditionsQueryError = AxiosError<unknown>


export function useGetApiCompendiumConditions<TData = Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumConditions>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumConditions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumConditions<TData = Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumConditions>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumConditions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumConditions<TData = Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves all standard D&D conditions.
 */

export function useGetApiCompendiumConditions<TData = Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCompendiumConditionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






