/**
 * Generated by orval 🍺
 * Do not edit manually.
 * D&D Game Map VTT API (.NET 10)
 * Virtual Tabletop API for maps, dynamic grids, token synchronization, and 5e spells.
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompendiumClassDto,
  CompendiumConditionDto,
  CompendiumMonsterDto,
  CompendiumRaceDto,
  CompendiumSpellDto,
  GetApiCompendiumMonstersParams,
  GetApiCompendiumSpellsParams
} from '../../model';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiCompendiumClassesResponse200TextPlain = {
  data: CompendiumClassDto[]
  status: 200
}

export type getApiCompendiumClassesResponse200ApplicationJson = {
  data: CompendiumClassDto[]
  status: 200
}

export type getApiCompendiumClassesResponse200TextJson = {
  data: CompendiumClassDto[]
  status: 200
}

export type getApiCompendiumClassesResponseSuccess = (getApiCompendiumClassesResponse200TextPlain | getApiCompendiumClassesResponse200ApplicationJson | getApiCompendiumClassesResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiCompendiumClassesResponse = (getApiCompendiumClassesResponseSuccess)

export const getGetApiCompendiumClassesUrl = () => {




  return `/api/Compendium/classes`
}

/**
 * @summary Retrieves all available D&D classes for character creation.
 */
export const getApiCompendiumClasses = async ( options?: Parameters<typeof customInstance>[1]): Promise<getApiCompendiumClassesResponse> => {

  return customInstance<getApiCompendiumClassesResponse>(getGetApiCompendiumClassesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiCompendiumClassesQueryKey = () => {
    return [
    `/api/Compendium/classes`
    ] as const;
    }


export const getGetApiCompendiumClassesQueryOptions = <TData = Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCompendiumClassesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCompendiumClasses>>> = ({ signal }) => getApiCompendiumClasses({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCompendiumClassesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCompendiumClasses>>>
export type GetApiCompendiumClassesQueryError = unknown


export function useGetApiCompendiumClasses<TData = Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumClasses>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumClasses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumClasses<TData = Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumClasses>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumClasses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumClasses<TData = Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves all available D&D classes for character creation.
 */

export function useGetApiCompendiumClasses<TData = Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumClasses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCompendiumClassesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiCompendiumRacesResponse200TextPlain = {
  data: CompendiumRaceDto[]
  status: 200
}

export type getApiCompendiumRacesResponse200ApplicationJson = {
  data: CompendiumRaceDto[]
  status: 200
}

export type getApiCompendiumRacesResponse200TextJson = {
  data: CompendiumRaceDto[]
  status: 200
}

export type getApiCompendiumRacesResponseSuccess = (getApiCompendiumRacesResponse200TextPlain | getApiCompendiumRacesResponse200ApplicationJson | getApiCompendiumRacesResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiCompendiumRacesResponse = (getApiCompendiumRacesResponseSuccess)

export const getGetApiCompendiumRacesUrl = () => {




  return `/api/Compendium/races`
}

/**
 * @summary Retrieves all available D&D races for character creation.
 */
export const getApiCompendiumRaces = async ( options?: Parameters<typeof customInstance>[1]): Promise<getApiCompendiumRacesResponse> => {

  return customInstance<getApiCompendiumRacesResponse>(getGetApiCompendiumRacesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiCompendiumRacesQueryKey = () => {
    return [
    `/api/Compendium/races`
    ] as const;
    }


export const getGetApiCompendiumRacesQueryOptions = <TData = Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCompendiumRacesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCompendiumRaces>>> = ({ signal }) => getApiCompendiumRaces({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCompendiumRacesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCompendiumRaces>>>
export type GetApiCompendiumRacesQueryError = unknown


export function useGetApiCompendiumRaces<TData = Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumRaces>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumRaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumRaces<TData = Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumRaces>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumRaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumRaces<TData = Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves all available D&D races for character creation.
 */

export function useGetApiCompendiumRaces<TData = Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumRaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCompendiumRacesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiCompendiumSpellsResponse200TextPlain = {
  data: CompendiumSpellDto[]
  status: 200
}

export type getApiCompendiumSpellsResponse200ApplicationJson = {
  data: CompendiumSpellDto[]
  status: 200
}

export type getApiCompendiumSpellsResponse200TextJson = {
  data: CompendiumSpellDto[]
  status: 200
}

export type getApiCompendiumSpellsResponseSuccess = (getApiCompendiumSpellsResponse200TextPlain | getApiCompendiumSpellsResponse200ApplicationJson | getApiCompendiumSpellsResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiCompendiumSpellsResponse = (getApiCompendiumSpellsResponseSuccess)

export const getGetApiCompendiumSpellsUrl = (params?: GetApiCompendiumSpellsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Compendium/spells?${stringifiedParams}` : `/api/Compendium/spells`
}

/**
 * @summary Searches spells by name filter and optional spell level.
 */
export const getApiCompendiumSpells = async (params?: GetApiCompendiumSpellsParams, options?: Parameters<typeof customInstance>[1]): Promise<getApiCompendiumSpellsResponse> => {

  return customInstance<getApiCompendiumSpellsResponse>(getGetApiCompendiumSpellsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiCompendiumSpellsQueryKey = (params?: GetApiCompendiumSpellsParams,) => {
    return [
    `/api/Compendium/spells`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiCompendiumSpellsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError = unknown>(params?: GetApiCompendiumSpellsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCompendiumSpellsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCompendiumSpells>>> = ({ signal }) => getApiCompendiumSpells(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCompendiumSpellsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCompendiumSpells>>>
export type GetApiCompendiumSpellsQueryError = unknown


export function useGetApiCompendiumSpells<TData = Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError = unknown>(
 params: undefined |  GetApiCompendiumSpellsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumSpells>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumSpells>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumSpells<TData = Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError = unknown>(
 params?: GetApiCompendiumSpellsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumSpells>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumSpells>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumSpells<TData = Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError = unknown>(
 params?: GetApiCompendiumSpellsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Searches spells by name filter and optional spell level.
 */

export function useGetApiCompendiumSpells<TData = Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError = unknown>(
 params?: GetApiCompendiumSpellsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumSpells>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCompendiumSpellsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiCompendiumMonstersResponse200TextPlain = {
  data: CompendiumMonsterDto[]
  status: 200
}

export type getApiCompendiumMonstersResponse200ApplicationJson = {
  data: CompendiumMonsterDto[]
  status: 200
}

export type getApiCompendiumMonstersResponse200TextJson = {
  data: CompendiumMonsterDto[]
  status: 200
}

export type getApiCompendiumMonstersResponseSuccess = (getApiCompendiumMonstersResponse200TextPlain | getApiCompendiumMonstersResponse200ApplicationJson | getApiCompendiumMonstersResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiCompendiumMonstersResponse = (getApiCompendiumMonstersResponseSuccess)

export const getGetApiCompendiumMonstersUrl = (params?: GetApiCompendiumMonstersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Compendium/monsters?${stringifiedParams}` : `/api/Compendium/monsters`
}

/**
 * @summary Searches monsters by name filter.
 */
export const getApiCompendiumMonsters = async (params?: GetApiCompendiumMonstersParams, options?: Parameters<typeof customInstance>[1]): Promise<getApiCompendiumMonstersResponse> => {

  return customInstance<getApiCompendiumMonstersResponse>(getGetApiCompendiumMonstersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiCompendiumMonstersQueryKey = (params?: GetApiCompendiumMonstersParams,) => {
    return [
    `/api/Compendium/monsters`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiCompendiumMonstersQueryOptions = <TData = Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError = unknown>(params?: GetApiCompendiumMonstersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCompendiumMonstersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCompendiumMonsters>>> = ({ signal }) => getApiCompendiumMonsters(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCompendiumMonstersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCompendiumMonsters>>>
export type GetApiCompendiumMonstersQueryError = unknown


export function useGetApiCompendiumMonsters<TData = Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError = unknown>(
 params: undefined |  GetApiCompendiumMonstersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumMonsters>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumMonsters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumMonsters<TData = Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError = unknown>(
 params?: GetApiCompendiumMonstersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumMonsters>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumMonsters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumMonsters<TData = Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError = unknown>(
 params?: GetApiCompendiumMonstersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Searches monsters by name filter.
 */

export function useGetApiCompendiumMonsters<TData = Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError = unknown>(
 params?: GetApiCompendiumMonstersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumMonsters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCompendiumMonstersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiCompendiumConditionsResponse200TextPlain = {
  data: CompendiumConditionDto[]
  status: 200
}

export type getApiCompendiumConditionsResponse200ApplicationJson = {
  data: CompendiumConditionDto[]
  status: 200
}

export type getApiCompendiumConditionsResponse200TextJson = {
  data: CompendiumConditionDto[]
  status: 200
}

export type getApiCompendiumConditionsResponseSuccess = (getApiCompendiumConditionsResponse200TextPlain | getApiCompendiumConditionsResponse200ApplicationJson | getApiCompendiumConditionsResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiCompendiumConditionsResponse = (getApiCompendiumConditionsResponseSuccess)

export const getGetApiCompendiumConditionsUrl = () => {




  return `/api/Compendium/conditions`
}

/**
 * @summary Retrieves all standard D&D conditions.
 */
export const getApiCompendiumConditions = async ( options?: Parameters<typeof customInstance>[1]): Promise<getApiCompendiumConditionsResponse> => {

  return customInstance<getApiCompendiumConditionsResponse>(getGetApiCompendiumConditionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiCompendiumConditionsQueryKey = () => {
    return [
    `/api/Compendium/conditions`
    ] as const;
    }


export const getGetApiCompendiumConditionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCompendiumConditionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCompendiumConditions>>> = ({ signal }) => getApiCompendiumConditions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCompendiumConditionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCompendiumConditions>>>
export type GetApiCompendiumConditionsQueryError = unknown


export function useGetApiCompendiumConditions<TData = Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumConditions>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumConditions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumConditions<TData = Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompendiumConditions>>,
          TError,
          Awaited<ReturnType<typeof getApiCompendiumConditions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompendiumConditions<TData = Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves all standard D&D conditions.
 */

export function useGetApiCompendiumConditions<TData = Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompendiumConditions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCompendiumConditionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






